### ISSUE TITLE
Task force

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#10]
Bonsoir je précise que ca va faire 100 fois que je suis le read me

Line 88 : Remplace YOUR TEAMSPEAK NAME by your Teamspeak's name

Exemple :
waitUntil {(["Lyeed Tanoa Life Teamspeak", (call TFAR_fnc_getTeamSpeakServerName)] call BIS_fnc_inString)};

Line 93 : Your channel name. Default : TaskForceRadio
et le task force switch niquel mais au bout d'une min le serveur met erreur et dit vous n'etes pas connecter sur le teamspeak du serveur. Par contre si je me met en admin nickel pas de problème

Cordialement

diag_log " Validation de présence sur le Teamspeak ...";
("initLayer" call BIS_fnc_rscLayer) cutText ["Validation de présence sur le Teamspeak", "BLACK FADED", 999999, true];
waitUntil {(["Aventura", (call TFAR_fnc_getTeamSpeakServerName)] call BIS_fnc_inString)};
diag_log " Présence validé";

	diag_log "<INIT> En attente de validation de votre présence dans le channel TaskForceRadio...";
	("initLayer" call BIS_fnc_rscLayer) cutText ["En attente de validation de votre présence dans le channel TaskForceRadio", "BLACK FADED", 999999, true];
	waitUntil {((call TFAR_fnc_getTeamSpeakChannelName) isEqualTo "TaskForceRadio")};
	diag_log "<INIT> Présence dans le channel TaskForceRadio validé";
Et j'ai même renomer pour voir mon serveur ts en TaskForceRadio

**Comment by Lyeed** [comment]
`waitUntil {(["Aventura", (call TFAR_fnc_getTeamSpeakServerName)] call BIS_fnc_inString)};`

Ton serveur teamspeak doit avoir Aventura dans son nom.
Le canal Taskforce pour Teamspeak doit s'appeler TaskForceRadio

Si ces deux cas sont validés, l'erreur vient de toi et je ne pourrais pas t'aider.
Je t'invite à revoir les modifications que tu as apportés au framework.

**Comment by boubablackmamba** [comment]
Merci je vais essayer de trouvé la soluce mais je vous remercie

**Comment by boubablackmamba** [comment]
Bonjour juste a toute hasard quelle version de task force radio utilisiez vous?
Cordialement

**Comment by Lyeed** [comment]
L'erreur vient de toi, ne remet pas en question TaskForceRadio ou sa version.

Si les joueurs se font kick c'est que tu as mal configuré le nom de ton Teamspeak dans la mission.
Tant que tu n'auras pas corrigé sa les kick continueront

**Comment by boubablackmamba** [comment]
Dsl je me suis peut-être mal exprimé je sais bien que çà na rien avoir avec la version. J'ai trouvé la solution au problème dans un autre fichier y avais du alysia a changer. Cordialement

**Comment by mecta02** [comment]
méme souci aucune modif apporter au framework :-(
