### ISSUE TITLE
Entreprises A à Z 

### ISSUE THREAD

**Issue by Taneino** [Lyeed/Framework_Tanoa_Life#102]
Bonjour Lyeed, 

J'ai lu des différentes issues par rapport à la création d'une entreprise. J'ai compris qu'il fallait la licence agri_coopt, et faire windows quelque part pour pouvoir créer l'entreprise..

Concrètement pourrais -tu m'expliquer plus en détails le fonctionnement de cela ? Je suis civil 

merci d'avance

**Comment by RtcSmocky** [comment]
Bonjour Taneino,

Tout d'abord tu dois être en possession de la licence qui te sert à créer une entreprise (configurable dans le fichier "**Config_Factions.hpp**") en l’occurrence "**agri_coopt**" dans ton cas.

Une fois cette licence tienne, tu fais simplement Windows sur un joueur et tu auras une interaction "**Entreprise**". Après à toi de choisir l'entreprise que tu veux mettre en place.
**Attention** car certaines entreprises font spawn un gros bâtiment alors attention aux joueurs aux alentours.
Une fois l'entreprise en place elle se transformera en palette de briques qu'il faudra remplir avec les composants nécessaire à sa création. Une fois les composants en place il suffira d’interagir avec la palette et de choisir construction (encore une fois attention à cette étape qui peut être dangereuse).
J'espère t'avoir aider en tout cas.

**Comment by MrAntoine** [comment]
Super je te remercie !

**Comment by Taneino** [comment]
Super merci !
