### ISSUE TITLE
alysiaclient_fnc_errorexit is undefined

### ISSUE THREAD

**Issue by Taneino** [Lyeed/Framework_Tanoa_Life#103]
Hello je suis de nouveau à l'attaque..
J'ai cette erreur lorsque je lance le serveur; j'ai un peu trifouiller partout sans trouvé d'où sa peux venir..

Logs Client : 

```
16:12:21 "<INIT> En attente de réponse du serveur..."
16:12:21 "<INIT> Vérification des mods..."
16:12:21 Error in expression <e pour vous connecter.", _check]] spawn AlysiaClient_fnc_errorExit;
};
diag_log >
16:12:21   Error position: <AlysiaClient_fnc_errorExit;
};
diag_log >
16:12:21   Error Variable indéfinie dans une expression: alysiaclient_fnc_errorexit
16:12:21 File mpmissions\__CUR_MP.Tanoa\initPlayerLocal.sqf..., line 46
```
Coter server rien d'anormal...

**Comment by Lyeed** [comment]
Bonjour,

Avez-vous changé le préfix utilisé par les fonctions ?
Vous pouvez retrouver cette fonction [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Tools/fn_errorExit.sqf)

**Comment by Taneino** [comment]
J'ai réinstaller la mission complète et cela semble fonctionner de nouveau ;)
