### ISSUE TITLE
Init building 

### ISSUE THREAD

**Issue by Taneino** [Lyeed/Framework_Tanoa_Life#105]
Bonjour, 

Je voudrais généré l’apparition sur la map, j'ai cru comprendre que cela se géré dans le InitBuilding. Par contre je ne comprend pas tous les params..

`["Oleander1","[7331.335938,8533.424805,0]",24.0478,-100,0,0,[]] call _CreateLocalVehicle;`

Classname, suivis des coordonnées, par contre les 4 nombre par la suite , a quoi correspondent-ils exactement ? 

Merci par avance :D

**Comment by Lyeed** [comment]
Bonjour,

Tu peux retrouver dans le fichier [init_buildings](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Inits/fn_init_buildings.sqf) la fonction qui est appelée et donc voir à quoi les paramètres servent.

La suite c'est la direction, une hauteur custom (-100 = pas de hauteur custom), la simulation, le vecteur et les scripts.
