### ISSUE TITLE
Inventaire virtuel dans le menu inventaire normal

### ISSUE THREAD

**Issue by ajnart** [Lyeed/Framework_Tanoa_Life#107]
Bonjour, sur une des screens dans le README, on peut voir que le virtual env est affiché dans l'inventaire normal. 
Quels sont les étapes à réaliser pour implémenter cette feature sur un autre serveur ? (Altis Life 5.0)

**Comment by ajnart** [comment]
Update : J'ai trouvé une ref à ``"poids"`` dans fn_virtual_menu_update_list 
donc je vais essayer de l'implémenter comme ça en remontant récursivement dans les appels de fonctions

**Comment by Lyeed** [comment]
Bonjour,

Je partage un framework complet et non des scripts à l'unités à installer indépendamment.
Si vous souhaitez extraire des fonctionnalités de la mission, vous allez devoir vous y prendre seul puisque mon support s'arrête à la résolution de bugs du framework.

**Comment by ajnart** [comment]
Pas de problème j'ai réglé ça de mon côté 😉

**Comment by Lyeed** [comment]
Parfait! Je clos le ticket.
