### ISSUE TITLE
2 petites questions 

### ISSUE THREAD

**Issue by z4khy** [Lyeed/Framework_Tanoa_Life#109]
bonjour lyeed,
Première chose merci du partage c'est super cool :-)
1er question : Je veux installer infistar cependant il m’oblige de mettre A3_infistar dans le modpack qu'on l'on distribue aux joueurs . As tu une solution ?

2em question : je voudrais faire en sorte que ce soit un membre du staff qui place les entreprises , mais je ne sait absolument pas comment faire, peux tu m'aiguiller stp?

Merci de tes réponses.(dsl d’être un boulet)

**Comment by Lyeed** [comment]
Bonjour,

1) Aucune idée, jamais utilisé. Je ne pense pas que tu en ais besoin.

2) Il suffit de donner la licence correspondante à la personne du staff
