### ISSUE TITLE
Attribution des entreprises.

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#11]
Bonjour, peut-on avoir un petit descriptif svp des attributions des entreprises svp cordialement.
autre question? pour rentrer la ligne de commande 
Player setVariable [“copLevel”, 1, true]; pour le batiment mattaust dans quel fichier je doit le mettre dans cette mission pour ouvrir les batiments?
Cordialement

**Comment by Lyeed** [comment]
Je pense que tu devrais prendre un peu de temps dans la mission pour comprendre comment elle fonctionne en jeu et dans le code.
Ton serveur est installé et doit fonctionner. A moins que tu ne rencontre des bugs, et il n'y en a pas beaucoup, mon assistance s'arrête là.
Ma démarche est un partage et non un assistanat

**Comment by boubablackmamba** [comment]
ok tres bien merci
