### ISSUE TITLE
Souci au changement de map

### ISSUE THREAD

**Issue by Gameforceindustrie** [Lyeed/Framework_Tanoa_Life#110]
Salut

J'ai ajouté le framework sans souci fonctionnel sur autre map,

Juste une légere erreur d'entry 

![image](https://user-images.githubusercontent.com/17122725/100893760-02c6a180-34bc-11eb-8568-532e3d98df0d.png)

Dont je n'arrive pas a voir j'ai pas que cella j'ai donc : 

15:48:49 Warning Message: No entry 'mpmissions\__CUR_MP.futurisland\description.ext/RscDisplayTablet/controls/VEHICLES_DATA_MAP.widthRailWay'.
15:48:49 Warning Message: '/' is not a value
15:48:49 Warning Message: No entry 'mpmissions\__CUR_MP.futurisland\description.ext/RscDisplayTablet/controls/FUEL_MAP.widthRailWay'.
15:48:49 Warning Message: '/' is not a value
15:48:49 Warning Message: No entry 'mpmissions\__CUR_MP.futurisland\description.ext/RscDisplayTablet/controls/DAB_MAP.widthRailWay'.
15:48:49 Warning Message: '/' is not a value
15:48:49 Warning Message: No entry 'mpmissions\__CUR_MP.futurisland\description.ext/RscDisplayTablet/controls/COMPAGNIES_MAP.widthRailWay'.
15:48:38 Warning Message: '/' is not a value

J'ai biensur chercher avant 

Merci à toi

**Comment by Lyeed** [comment]
Salut

L'erreur n'a pas l'air d'être lié à la nouvelle carte mais plutôt à des controls dans le dialog de la tablette (RscDisplayTablet)

**Comment by Lyeed** [comment]
Le soucis a été corrigé dans [ce commit](https://github.com/Lyeed/Framework_Tanoa_Life/commit/f62edd39500fbb88e7103bdd8a9650a83a29913c)
