### ISSUE TITLE
Soucis base de donnée, Identités sur le passeport + tablette 

### ISSUE THREAD

**Issue by AntoninWayne** [Lyeed/Framework_Tanoa_Life#111]
Bonsoir,
J'ai un soucis avec la base de données, une fois l'inscription effectuer, l'age sur la tablette ne correspond pas a celle indiqué, il m'indique "18 ans" sur tout le monde. 
Le passeport n'affiche pas le nom de la personne, l'age en globalité l'identité a gauche.
J'ai essayé d'effectuer plusieurs manipulations, changer de base de donnée ect.., rien ne fonctionne.
Autre soucis avec le servercommand a chaque redémarre une erreur apparait "Failed attempt to execute serverCommand '#lock/uncloak' by server." j'ai la bonne commande du RCON dans le tanoa-server.
Cordialement, Antonin.

**Comment by AntoninWayne** [comment]
Bonsoir, Je reviens vers vous suite a mon problème pour le RCON, soucis résolu mais j'ai toujours le même soucis avec l'âge et l'identité sur le passeport.
J'ai regarder les autres Issues, j'ai correctement mis la dernière version de la database.sql, aucun résultat.
Cordialement Antonin.

**Comment by Lyeed** [comment]
Bonjour,

Si la tablette affiche 18 ans et pas de nom pour le joueur c'est qu'il n'a pas de données à afficher, 18 étant la valeur par défaut de l'âge. Les données peuvent être manquantes ou invalide. Je vous suggère de comparer les données de votre personnage avec celles d'un nouveau joueur.
