### ISSUE TITLE
Conservation de l'inventaire

### ISSUE THREAD

**Issue by CEKTAHT0** [Lyeed/Framework_Tanoa_Life#113]
Salut. Il ya un problème. Lorsque le serveur se déconnecte d'urgence, le joueur manque tous les articles récemment achetés, le point d'arrêt n'est pas enregistré. Il y a un retour en arrière complet, toutes les actions. Cela va irriter les joueurs. Dites-moi comment vous pouvez résoudre ce problème?

**Comment by Lyeed** [comment]
Bonjour,

Le serveur n'est pas supposé s'arrêter en urgence sans appeler la fonction de sauvegarde. Les horaires de redémarrage doivent être indiqués dans la configuration du pbo serveur pour que ce dernier puisse sauvegarder le nécessaire à l'heure.

**Comment by CEKTAHT0** [comment]
Merci pour la réponse
