### ISSUE TITLE
Erreur au spawn du personnage ( no entry )

### ISSUE THREAD

**Issue by AntoninWayne** [Lyeed/Framework_Tanoa_Life#115]
Bonjour Lyeed.
Petit soucis avec une erreur que je n'arrive pas a résoudre. (je suis toujours sur Tanoa, sans aucune modification du GPS)
l'erreur s'affiche a chaque spawn du personnage.
voici l'erreur:

![3](https://user-images.githubusercontent.com/78716611/113760041-1443e280-9716-11eb-969c-4bfaa7ed9477.png)

Je te remercies d'avance,
Cordialement, Wayne.

**Comment by Lyeed** [comment]
Hello

Dans le classe RscTitlePlayer tu as un control GPS_MAP, essaye de lui ajouter la propriété `widthRailWay = 1;`

**Comment by AntoninWayne** [comment]
Bonsoir !
Je te remercie pour ta réponse ^^
Ça marche, je vais essayer, tu me confirmes, je l'ajoute comme ceci :
![b75e40e7d0f864d5e1e170102c6a46db](https://user-images.githubusercontent.com/78716611/116001781-94af8200-a5f6-11eb-897a-3df5692b4597.png)

**Comment by AntoninWayne** [comment]
Soucis réglés, je te remercie ! 
Cordialement, Wayne
