### ISSUE TITLE
Problème respawn

### ISSUE THREAD

**Issue by WilkTw** [Lyeed/Framework_Tanoa_Life#116]
Bonjour,

J'ai installé la mission du serveur et les problèmes liés aux mods que j'ai installé moi-même, jusqu'à tout fonctionné parfaitement.

Cependant je rencontre un problème au moment du respawn en soin intensif.
Après avoir cliqué sur le bouton "aller en soin intensif", mon écran reste noir avec la mention "Vous êtes en soin intensif".

Lorsque je déco-reco, j'apparait instantanément au point de respawn mentionné, c'est à dire "respawn_guerrila)

Merci d'avance pour votre aide.

Bonne journée

**Comment by Lyeed** [comment]
Bonjour,

Les marqueurs de respawn sont référencés dans [ce fichier](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Factions.hpp) selon chaque faction. Le marqueur pour chaque faction doit être présent dans le .sqm avec le nom de variable qui correspond.

**Comment by WilkTw** [comment]
Bonjour, effectivement j'avais oublié de configurer le respawn_west.
Je viens de réessayer, et cela me bloque toujours sur l'écran noir. J'ai accès cepandant à mon inventaire I, ma tablette etc pendant l'écran noir.
Je ne comprends pas non plus pourquoi il me prenne seulement 1$ pour les frais médicaux.
https://zupimages.net/viewer.php?id=21/18/4j4o.jpg
https://zupimages.net/viewer.php?id=21/18/r7kn.jpg
https://zupimages.net/viewer.php?id=21/18/wu1e.jpg

Merci d'avance.

**Comment by WilkTw** [comment]
Bonjour, le soucis viens de ma mission.sqm.

Je vais essaye de trouver d'où vient le problème.

Merci de votre aide.
