### ISSUE TITLE
traitement des ressources

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#12]
Bonjour j'ai trouvé toute les réponses auquel je vous ai posé sauf que je ne trouve aucun traitement sur ma p c un beug ? car j'ai changer de map comment les retrouvé et les placer? je parle de ceux de base pas les entreprises

**Comment by Lyeed** [comment]
Je ne fais du support que sur la version vanilla du framework. A partir du moment où tu apportes des modifications autre que de la config ce n'est plus de mon ressort.
