### ISSUE TITLE
Probleme de demarage serveur

### ISSUE THREAD

**Issue by nemesisgroup** [Lyeed/Framework_Tanoa_Life#13]
Bonjour, je vous contacte car j'ai un soucis avec la mission, j'ai bien suivi le readme et regarder dans les issue, j'ai bien corriger le $préfix$ et est regler le extdb mais j'ai toujours le soucis.

Mon fichier extdb:

`[Main]
Version = 5

;Threads = 0  
; Default Value is the number of CPU Cores Detected (max value is 6, min value is 2)

Randomize Config File = false
;This is a legacy option to randomize config file for Arma2 Servers. Only for Windows Builds

[Rcon]
;; This is functional, should be working fine. Just needs abit of testing on a $
;; Allow for changing Address for those running server in a VM environment.
IP = 127.0.0.1
Port = 2302

;; Rcon Password i.e Battleye/beserver.cfg
Password = ******

;; Bad Player Name Checks
;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
Bad Playername Enable = false
Bad Playername Kick Message = Bad Player Name

;; By default : is a bad character (used as seperator for extDB2 Calls (this is hardcoded in)
;;Bad Playername Strings = (:):{:}
;;Bad Playername Regex_1 = [:alnum:]
;;Bad Playername Regex_2 = [:alnum:]
;;Bad Playername Regex_3 = [:alnum:]

;; Whitelisting / Reserve Slots
;;		This will only work if your mission / mod has started extDB2 Rcon. i.e 9:START_RCON:RCON
Whitelist Enable = false
Whitelist Kick Message = Only Reserved Slots Left

Whitelist Public Slots = 999

;; Database settings to use (Optional)
Whitelist Database = MySQL_Example
Whitelist SQL Prepared Statement = SELECT CASE WHEN EXISTS(SELECT UID FROM PlayerInfo WHERE BattlEyeGUID=? AND Whitelisted=1) THEN 1 ELSE 0 END
Whitelist Kick on SQL Query Failed = false

;; Hardcoded BEGuids for whitelisted players
;Whitelist BEGuids = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx : yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

[Steam]
;; This is for VAC Protocol for VAC Bans + Steam Friends.
;; https://steamcommunity.com/dev/apikey
API Key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[VAC]
;; This feature requires Steam + Rcon to be enabled.
;; Also this feature is called via SQF Code atm, i.e it doesn't auto detect players joining server yet....
Auto Ban = true

;; For Player to get banned ( their total VAC Bans => NumberOfVACBans)  AND ( Days Since their Last Ban was <= DaysSinceLastBan)
;; This is also used extDB Protocol VAC:VACBanned returned results

NumberOfVACBans = 1
DaysSinceLastBan = 999999999
BanDuration = 0
;; 0 = Forever, otherwise its x Minutes
BanMessage = Steam VAC Banned

[Log]
;; Flush Logs after each write, more work on Harddrive
Flush = true

[tanoa]
Type = MySQL
Name = tanoa

Username = ******
Password = **********

IP = 127.0.0.1
Port = 3306

;minSessions = 2
idleTime = 60

compress = false
; Really should only use this if MySQL server is external. Also only for MySQL

Secure Auth = true
; Recommend you turn this on  http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html#option_mysql_secure-auth

[SQLite_Example]
Type = SQLite
Name = sqlite.db

minSessions = 1
; minSession Default Value = 1

;maxSessions = 4
; maxSession Default Value = number of Main->Threads
; 	You really should leave this value alone
idleTime = 60
; idleTime no Default Value yet, needs to be defined.
; 	idleTime is the time before a database session is stopped if not used. 
;	If Database Sessions are greater than minSessions`

( j'ai biensur caché l'id et le mdp )

et mes RPT: 

`2018/05/16, 21:23:20 Error: selection  missing in memory LOD of model stephdub_alysiarp_plot\plot.p3d
2018/05/16, 21:23:21 Strange convex component67 in lemon_bar_biker\lemon_bar_biker.p3d:geometryPhys
2018/05/16, 21:23:21 Strange convex component68 in lemon_bar_biker\lemon_bar_biker.p3d:geometryPhys
2018/05/16, 21:23:21 Strange convex component69 in lemon_bar_biker\lemon_bar_biker.p3d:geometryPhys
2018/05/16, 21:23:21 Strange convex component70 in lemon_bar_biker\lemon_bar_biker.p3d:geometryPhys
2018/05/16, 21:23:21 Strange convex component71 in lemon_bar_biker\lemon_bar_biker.p3d:geometryPhys
2018/05/16, 21:23:21 "default/BIS_fnc_log: [script] initServer.sqf"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] BIS_fnc_initParams (0 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0.999451 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] BIS_fnc_keyframeAnimation_init (6.00433 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] SAN_Headlamp_fnc_PostInit (0 ms)"
2018/05/16, 21:23:21 Error in expression <ffectCreate ["ColorCorrections", 2500];
SUPER_PPEffect ppEffectAdjust [1, 1, -0.>
2018/05/16, 21:23:21   Error position: <SUPER_PPEffect ppEffectAdjust [1, 1, -0.>
2018/05/16, 21:23:21   Error Undefined variable in expression: super_ppeffect
2018/05/16, 21:23:21 File \SUPER_flash\init.sqf [SUPER_fnc_InitFlashBang], line 2
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] SUPER_fnc_InitFlashBang (0 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] BIS_fnc_reviveInit (0 ms)"
2018/05/16, 21:23:21 [8674,78.783,0,"XEH: PostInit started. MISSIONINIT: missionName=Tanoa-Life, missionVersion=53, worldName=Tanoa, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false"]
2018/05/16, 21:23:21 [8674,78.808,0,"CBA_VERSIONING: cba=3.2.1.170227, "]
2018/05/16, 21:23:21 [8674,78.813,0,"XEH: PostInit finished."]
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] CBA_fnc_postInit (29.9988 ms)"
2018/05/16, 21:23:21 "default/BIS_fnc_log: [postInit] TFAR_fnc_TaskForceArrowheadRadioInit (0.999451 ms)"
2018/05/16, 21:23:21 EPE manager release (0|2|0)
2018/05/16, 21:23:22 Starting mission:
2018/05/16, 21:23:22  Mission file: Tanoa-Life
2018/05/16, 21:23:22  Mission world: Tanoa
2018/05/16, 21:23:22  Mission directory: mpmissions\Tanoa-Life.Tanoa\
2018/05/16, 21:23:23 "default/BIS_fnc_log: [BIS_fnc_preload] ----- Initializing scripts in Tanoa-Life -----"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [recompile] recompile BIS_fnc_missionTasksLocal"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [recompile] recompile BIS_fnc_missionConversationsLocal"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [recompile] recompile BIS_fnc_missionFlow"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] BIS_fnc_feedbackMain (0.999451 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] BIS_fnc_missionHandlers (0 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] BIS_fnc_storeParamsValues (0 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] ""DeltaTime computation started"""
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] BIS_fnc_keyframeAnimation_deltaTime (0 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] SAN_Headlamp_fnc_Init (0 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] BIS_fnc_getServerVariable (0 ms)"
2018/05/16, 21:23:23 [8677,80.929,0,"XEH: PreInit started. v3.2.1.170227"]
2018/05/16, 21:23:23 [XEH]: Usage of deprecated Extended Event Handler "fired". Use "firedBIS" instead. Path: @Alysia\bin\config.bin\Extended_Fired_EventHandlers\Man.
2018/05/16, 21:23:23 [XEH]: One or more children of class Man do not support Extended Event Handlers. Fall back to loop.
2018/05/16, 21:23:23 [8677,81.164,0,"XEH: PreInit finished."]
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] CBA_fnc_preInit (235.001 ms)"
2018/05/16, 21:23:23 "default/BIS_fnc_log: [preInit] AlysiaClient_fnc_preInit (5.00488 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [script] initServer.sqf"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0.999451 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] BIS_fnc_initParams (0 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] BIS_fnc_keyframeAnimation_init (6.00433 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] SAN_Headlamp_fnc_PostInit (0 ms)"
2018/05/16, 21:23:24 Error in expression <ffectCreate ["ColorCorrections", 2500];
SUPER_PPEffect ppEffectAdjust [1, 1, -0.>
2018/05/16, 21:23:24   Error position: <SUPER_PPEffect ppEffectAdjust [1, 1, -0.>
2018/05/16, 21:23:24   Error Undefined variable in expression: super_ppeffect
2018/05/16, 21:23:24 File \SUPER_flash\init.sqf [SUPER_fnc_InitFlashBang], line 2
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] SUPER_fnc_InitFlashBang (0 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] BIS_fnc_reviveInit (0 ms)"
2018/05/16, 21:23:24 [8677,81.479,0,"XEH: PostInit started. MISSIONINIT: missionName=Tanoa-Life, missionVersion=53, worldName=Tanoa, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false"]
2018/05/16, 21:23:24 [8677,81.501,0,"CBA_VERSIONING: cba=3.2.1.170227, "]
2018/05/16, 21:23:24 [8677,81.506,0,"XEH: PostInit finished."]
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] CBA_fnc_postInit (27.9999 ms)"
2018/05/16, 21:23:24 "default/BIS_fnc_log: [postInit] TFAR_fnc_TaskForceArrowheadRadioInit (0.999451 ms)"
2018/05/16, 21:23:24 c:\bis\source\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
2018/05/16, 21:23:24  Mission id: 338c74b2c855a8e1ca664f48b54b4b9b9a24b6c3
2018/05/16, 21:23:24 Warning Message: Script Tanoa-Server\fn_initServer.sqf not found
2018/05/16, 21:23:24 Attempt to override final function - bis_fnc_storeparamsvalues_data
2018/05/16, 21:23:24 "default/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 879.997 ms -----"
2018/05/16, 21:23:59 Unaccessible
2018/05/16, 21:23:59 Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
2018/05/16, 21:23:59   Error position: <addEventHandler [_x, format ['call cba_x>
2018/05/16, 21:23:59   Error Foreign error: Unknown enum value: "FiredBis"
2018/05/16, 21:23:59 File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents], line 1945
2018/05/16, 21:23:59 Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
2018/05/16, 21:23:59   Error position: <addEventHandler [_x, format ['call cba_x>
2018/05/16, 21:23:59   Error Foreign error: Unknown enum value: "InitPost"
2018/05/16, 21:23:59 File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents], line 1945
2018/05/16, 21:26:54 Deinitialized shape [Class: "C_Soldier_VR_F"; Shape: "a3\characters_f_bootcamp\common\vr_soldier_f.p3d";]
2018/05/16, 21:26:55 Deinitialized shape [Class: "Skyline_Man_Alysia_01_F"; Shape: "a3\characters_f\civil\c_poloshirtpants.p3d";]
2018/05/16, 21:26:55 c:\bis\source\stable\futura\lib\network\networkserver.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
2018/05/16, 21:26:56 Extensions:`

(j'ai mit que la fin car on est limité en ligne )

deja il ne trouve pas le "fn_initServer.sqf" je ne comprend pas pourquoi.
et quand je me connecte je suis sur (en attente d'une réponse du server)

Merci d'avance de votre aide, cordialement.

**Comment by Draxprodd** [comment]
As-tu pack le Tanoa-Server en pbo ?

**Comment by Draxprodd** [comment]
Ton extdb2...

Tu peux me dire à quoi il  ressemble ? (screen)

**Comment by nemesisgroup** [comment]
![extdb 2](https://user-images.githubusercontent.com/39350373/40182532-ee737440-59eb-11e8-920c-e51fa27afc34.PNG)
![extdb 1](https://user-images.githubusercontent.com/39350373/40182533-ee9e66a0-59eb-11e8-905e-8b09adee8139.PNG)
 

comme ça ou le fichier en lui meme ?

**Comment by Lyeed** [comment]
`Warning Message: Script Tanoa-Server\fn_initServer.sqf not found`

S'il ne trouve Tanoa-Server\initServer.sqf c'est que tu n'as pas retiré le retour à la ligne dans le $PREFIX$

**Comment by nemesisgroup** [comment]
oui je l'ai bien retirer le retour a la ligne.

**Comment by Lyeed** [comment]
Dans ce cas l'erreur n'est plus celle indiquée dans le fichier de log.
Si l'erreur initiale est résolue, pourrais-tu ouvrir une nouvelle issue pour ton nouveau problème ?
Merci

**Comment by nemesisgroup** [comment]
le problème étant que ça me fait toujours la même erreur.

**Comment by Draxprodd** [comment]
Ton extDB2 est totalement pas celui-là..
Tu as la version source, et non build.

**Comment by nemesisgroup** [comment]
PROBLÉME RÉSOLU ! j'avais juste pas créer le addons dans mon @Tanoa-Server 😂  je ferme l'issue, merci de votre aide !! :D
