### ISSUE TITLE
Erreur lors de la connexion au serveur. 

### ISSUE THREAD

**Issue by psika26** [Lyeed/Framework_Tanoa_Life#15]
Bonjour à tous quand je me connecte au serveur j'ai cette erreur qui apparaît :  
"Une erreur est survenue lors du chargement de vos données. Veuillez vous reconnecter ou contacter un administrateur si le problème persiste"

Je ne vois pas d'où viens le soucis. Merci de votre aide.

**Comment by Lyeed** [comment]
Bonjour,

Pourriez-vous pull la dernière version du git et réessayer.

Si des erreurs persistent merci de fournir les fichiers suivants : 
- Log rpt serveur de la session
- Log rpt client de la session
- derniers logs Extdb3

**Comment by psika26** [comment]
https://pastebin.com/MNFLa3wc  --> log serveur
https://pastebin.com/vUp9LQnH ---> log extdb

**Comment by psika26** [comment]
logs client en 3 parties : 
https://hastebin.com/igunahoroq.coffeescript
https://hastebin.com/uceyiniket.apache
https://hastebin.com/uvuvokugij.coffeescript

**Comment by Lyeed** [comment]
Pourriez-vous me fournir les trois fichiers de logs issues d'une même heure / session de test.
Le serveur n'indique pas d'erreur lié à la base de donnée alors que le client n'arrive à pas à récupérer ses informations correctement.

**Comment by psika26** [comment]
Voici en pièce jointe tous les logs que vous avez demandé : 

- Log Serveur : https://mega.nz/#!VhlTEJgL!pPO5GaG-48DKiLtVqcLX_4wwye8JGyuvBYYDfotSHcQ
- Log Client : https://mega.nz/#!Fs8llRgC!Y_z-NLesVSv40D_cXX5Jg4hoZRz-kc0LliEmgzGlBbo
- Log ExtDB : https://mega.nz/#!Fs8llRgC!Y_z-NLesVSv40D_cXX5Jg4hoZRz-kc0LliEmgzGlBbo

**Comment by Lyeed** [comment]
Fixé
