### ISSUE TITLE
Bugs Divers

### ISSUE THREAD

**Issue by psika26** [Lyeed/Framework_Tanoa_Life#16]
Bonjour à tous, 

Quelques infos avant de commencer : 
Version du Framework et de la base de données : Dernière mise en ligne. 
Modifications effectuées : Juste des shops. 
Manipulations : Réinstallation sur une autre machine sans rien modifier : Toujours les mêmes bugs. 

Log Client - Serveur - ExtDB3 : https://mega.nz/#F!BgdHwACR!ghSOd9E4MnDcIZStom-otw

Bug n°1 : Toutes les personnes qui crées leurs personnages ont 18 ans alors qu'ils devaient en avoir 25, 30 etc ... : https://image.noelshack.com/fichiers/2018/32/3/1533749566-20180808183957-1.jpg

Bug n°2 : Lorsque qu'on regarde les papiers d'une personne toutes les infos sauf les licences sont remplacés par INCONNU comme pour l'âge, etc ... 

Bug n°3 : Même soucis que le bug n°2 mais pour les véhicules : https://image.noelshack.com/fichiers/2018/32/3/1533749565-20180808183954-1.jpg

Bug n°4 : Tous les joueurs qui ont aucune autorisation spéciale peuvent retirer les licences d'un autre joueur via le porte-feuille de celui-ci.

Bug n°5 : Quand on va dans la rubrique Gouv et dans la sous-rubrique taxe et qu'on ferme la tablette quand on veut la rouvrir on est bloqué sur l'écran d’accueil de celle-ci. 

Merci de votre aide.

**Comment by mecta02** [comment]
Bonjour merci pour le partage je n'arrive pas a crée de société aurai tu des précision a se sujet merci

**Comment by Lyeed** [comment]
Merci d'ouvrir une nouvelle issue pour ton probleme @mecta02.
De plus essaye de fournir des logs

**Comment by mecta02** [comment]
oups dsl :-(

**Comment by Slenderwan** [comment]
Salut ! J'ai exactement les mêmes problèmes. A ++

**Comment by Lyeed** [comment]
J'ai push une corrigé concernant l'âge.
Pour un suivi plus simple des tickets merci d'en faire un par problème 😄
