### ISSUE TITLE
entreprise 

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#17]
bonour je ne trouve pas le moyen de crée une entreprise via la tablette . sa fait 4 heures que je cherche mais la ces le flous total :-(

les log rpt arrive :-)

**Comment by mecta02** [comment]
https://mega.nz/#!Sr5SkCQL

**Comment by Lyeed** [comment]
Pour créer une entreprise cela se passe par le menu d'interaction Windows. Il faut avoir les permissions.

Voici la condition de l'option du menu
```
(
	isClass(missionConfigFile >> 'ALYSIA_FACTIONS' >> str(playerSide) >> 'companies' >> 'create') &&
	(
		(getNumber(missionConfigFile >> 'ALYSIA_FACTIONS' >> str(playerSide) >> 'companies' >> 'create' >> 'rank') <= (player getVariable ['rank',0])) &&
		(
			(getText(missionConfigFile >> 'ALYSIA_FACTIONS' >> str(playerSide) >> 'companies' >> 'create' >> 'license') isEqualTo '') ||
			([getText(missionConfigFile >> 'ALYSIA_FACTIONS' >> str(playerSide) >> 'companies' >> 'create' >> 'license')] call AlysiaClient_fnc_hasLicense)
		)
	)
) && (
	getNumber(missionConfigFile >> 'ALYSIA_FACTIONS' >> str(side(g_interaction_target)) >> 'companies' >> 'owner') isEqualTo 1
)
```

**Comment by mecta02** [comment]
etant mon premier serveur je tavouerai que j'ai un peut de mal a comprendre pourtant je fait de mon mieu

**Comment by mecta02** [comment]
si tu peut men dire un peut plus ces toujours bien d'apprendre

**Comment by mecta02** [comment]
ces bons jai reussi a comprendre

**Comment by mecta02** [comment]
si tu a un tipee ou un paypal nhesite pas

**Comment by jeremy16110** [comment]
Bonjour je trouve pas comment ajouter les permition pour la creation d'entreprise
