### ISSUE TITLE
Atm

### ISSUE THREAD

**Issue by cjeje84** [Lyeed/Framework_Tanoa_Life#20]
Bonjour et un énorme merci pour commencer.

J'aimerais savoir comment fonctionne les atm s'il vous plaît car je ne peut pas les utiliser y à t'il une commande admin a faire avant merci d'avance.

**Comment by Lyeed** [comment]
Bonjour,

Il faut faire la touche Windows devant un ATM

**Comment by cjeje84** [comment]
Merci à vous et vraiment merci pour votre travail
