### ISSUE TITLE
Problème avec entreprises

### ISSUE THREAD

**Issue by JeDebute01** [Lyeed/Framework_Tanoa_Life#21]
Merci beaucoup à toi pour ton travail. 
J'ai un soucis avec la création d'entreprise. Lorsque je vais dans le menu Y, j'ai aucune possibilité de créer une entreprise et j'ai aucune action possible avec windows. J'ai du rater quelques choses... Une licence à donné et comment la donné svp? Je te remercie d'avance et merci encore !

**Comment by Lyeed** [comment]
Bonjour,

La création d'une entreprise se fait à partir du menu d'interaction avec un joueur. Tu dois posséder les conditions indiquées pour ta faction dans Config_Factions.
