### ISSUE TITLE
Problèmes de recrutements 

### ISSUE THREAD

**Issue by FR-Maxence** [Lyeed/Framework_Tanoa_Life#22]
Bonjour,

Quand tu veux recruter quelqu’un dans une faction ( armée, garde ou samu) c'est impossible aucun joueur n'est répertoriée dans la tablette

**Comment by Lyeed** [comment]
Bonjour,

Vous pouvez trouver la condition d'affichage d'un civil dans la tablette dans ce fichier :  
 `https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/TanoaLife.Tanoa/core/Game/Tablet/fn_APP_faction_leader_officeHandler.sqf`

Condition : 
`if (((side _x) isEqualTo civilian) && !(isNil {_x getVariable "realname"})) then`

**Comment by FR-Maxence** [comment]
![image](https://user-images.githubusercontent.com/37456624/45238040-b68e5600-b2e0-11e8-8686-9c3010b5b62f.png)

Rien ni fait, la condition est bien là mais le menu reste vide dans toutes les factions.

**Comment by psika26** [comment]
Salut j'ai le même soucis.

**Comment by Lyeed** [comment]
Aucun element du menu ne semble contenir de valeur, y a t-il une erreur côté client/serveur/extdb?

**Comment by FR-Maxence** [comment]
Non, aucune erreur ne s'affiche

**Comment by psika26** [comment]
Je vais faire un diag_log et tester

**Comment by Lyeed** [comment]
L'erreur est t-elle toujours présente ? Avez-vous plus d'informations à fournir dessus ?

**Comment by CHL198011** [comment]
J'ai aussi rencontré un tel problème.

**Comment by Lyeed** [comment]
Un commit vient d'être fait pour corriger le problème de l'application
