### ISSUE TITLE
Entreprise ; 

### ISSUE THREAD

**Issue by Loic24** [Lyeed/Framework_Tanoa_Life#23]
Bonjour / Bonsoir , cela fait 6 jour que je cherches apres le solution pour vos entreprise j'ai meme regarder les probleme deja régler mais je ne vois rien a ma solution , pas de création d'entreprise rien , sauriez vous m'eclaircir?

**Comment by Loic24** [comment]
oui j'ai regarder et c'est que le gbm? qui peuvent le faire la création... et tout ce qui est panneau alysia et sur le gps le nom alysia peut-on le modifié?

**Comment by Lyeed** [comment]
Pour modifier le nom sur le gps tu peux utiliser les psd sur le répo GitHub
Concernant la création d'une entreprise tu dois avoir la licence et le rank indiqué dans Config_Faction.

**Comment by Loic24** [comment]
D'accords merci beaucoup lyeed ! Continue tu le dev sur arma 3 ? Ou-a-tu tout arrété?

**Comment by Lyeed** [comment]
Je suis actuellement dans l'association Projets Edaly qui a un serveur RPG en développement sur A3
