### ISSUE TITLE
Prison

### ISSUE THREAD

**Issue by JeDebute01** [Lyeed/Framework_Tanoa_Life#24]
Salut et merci pour ton travail !
J'ai un soucis avec les prisons, GAV etc etc. J'ai beau changé les positions pour envoyer et sortir les gens, cela ne fonctionne pas chez moi. J'ai aucune option sur windows sur le joueur et la seule action que j'ai sur la cellule en fer, c'est pour l'acheter. Aucune possibilité d'envoyer les gens en prison du coup :) (A part les fusiller mais c'est pas démocratique il parait xD)

	class Land_Gaol_Main
	{
		name = "Centre de réhabilitation";
		sides[] = {"WEST"};
		uniform = "Skyline_Uniforme_Prisonnier_01_F";
		// Changé ici: 
                exit[] = {7200.82,8250.2,0.00141907};
		escape_distance = 100;
		//changé ici 
                arrest_pos[] = {7200.82,8250.2,0.00141907};

Il n'y a que cela à changer ici? Et normalement cela fonctionne? Un autre endroit à faire? D'autre condition à remplir? (type de bâtiments etc etc)
Je te remercie !

**Comment by Lyeed** [comment]
Bonjour,

La prison n'est pas effective, les scripts/config n'ont pas été mis à jour pour la version Tanoa du framework.
Tu ne pourras donc pas l'utiliser dans y appliquer/corriger tes propres modifications.

Je te laisse donc décider du sort de tes prisonniers 😉

**Comment by JeDebute01** [comment]
Je te remercie 👍
