### ISSUE TITLE
Probleme Entreprise

### ISSUE THREAD

**Issue by MuTicax** [Lyeed/Framework_Tanoa_Life#25]
Bonjour j'aurai un petit probleme je n'arrive pas a creer d'entrepise car je ne trouve pas l'endroit du panneau 

Merci d'avance !

**Comment by Lyeed** [comment]
Duplicate [#21](https://github.com/Lyeed/Framework_Tanoa_Life/issues/21), [#23](https://github.com/Lyeed/Framework_Tanoa_Life/issues/23), [#17](https://github.com/Lyeed/Framework_Tanoa_Life/issues/17)
