### ISSUE TITLE
Question Mods

### ISSUE THREAD

**Issue by MuTicax** [Lyeed/Framework_Tanoa_Life#26]
Bonjour, je voudrai vous demander si il y aurai possibilité d'avoir les mods d'Alysia avec la garde républicaine ou m'indiquer ou je pourrai les trouver 

Coridalement Maxence et Merci d'avance 

PS : Excuser moi pour le message d'entreprise je n'avais pas vue la catégorie "Closed" Et super Framework ;)

**Comment by Lyeed** [comment]
La garde républicaine n'est pas présente dans les addons distribués avec le framework.

Concernant les prix des véhicules et des objets tu peux les modifier à partir des différents fichiers de config dans la mission

https://github.com/Lyeed/Framework_Tanoa_Life/tree/master/Tanoa-Life.Tanoa/configs/GameConfigs

**Comment by MuTicax** [comment]
Merci pour votre répouse j'ai une derniere question comment fait on pour changer la couleur des vehicules ?

**Comment by Lyeed** [comment]
La couleur des véhicules provient directement de la config de chaque véhicule.
