### ISSUE TITLE
Il n'y a pas d'usines de traitement pour tous les civils sur la carte.

### ISSUE THREAD

**Issue by CHL198011** [Lyeed/Framework_Tanoa_Life#27]
Je n'ai pas trouvé d'endroit où traiter le bois sur la carte.

**Comment by FR-Maxence** [comment]
Faut une entreprise adaptée à la ressource pour traiter les ressources (Bois = scierie)

**Comment by CHL198011** [comment]
Cependant, je n'ai pas trouvé la scierie sur la carte.

**Comment by Lyeed** [comment]
Duplicate [#21](https://github.com/Lyeed/Framework_Tanoa_Life/issues/21), [#23](https://github.com/Lyeed/Framework_Tanoa_Life/issues/23), [#17](https://github.com/Lyeed/Framework_Tanoa_Life/issues/17)

**Comment by CHL198011** [comment]
Est-ce un bug? Ou voulez-vous vérifier d'autres problèmes pour résoudre ce problème?

**Comment by Lyeed** [comment]
Te rends tu compte que t'as question a déjà été posée de nombreuses fois et que tu as ouvert une issue sans prendre la peine d'aller lire celles qui sont fermées et qui possèdent les informations que tu recherches ?

**Comment by CHL198011** [comment]
> 您是否意识到您的问题已经被多次询问并且您已经打开了一个问题而没有费心阅读那些已经关闭并且有您正在寻找的信息的人？

Désolé, je ne connais pas le français, j'utilise Google Translate. Ce n'est pas facile pour moi de faire fonctionner le serveur.

**Comment by Lyeed** [comment]
Oh you should have said it. 

Processes are included in the company system.
You should first build a wood company for example to be able to process wood.

**Comment by Lyeed** [comment]
GDM (blufor) is like a police/military faction. They cannot own a company

**Comment by CHL198011** [comment]
> Once you start the building of a company you can target it and open your admin menu with Y -> staff -> Construire (build).
> This will skip the construction step that has to be done by players

Il semble que je comprends ce que vous voulez dire, je dois le tester.

**Comment by CHL198011** [comment]
> Once you start the building of a company you can target it and open your admin menu with Y -> staff -> Construire (build).
> This will skip the construction step that has to be done by players

Merci beaucoup, je peux maintenant construire la société, mais la vidéo que j'ai vue dans YOUTUBE montre qu’il existe une usine fixe sur la carte. Les joueurs ordinaires peuvent collecter des matières premières puis les traiter, mais mon propre serveur ne peut pas les afficher.

**Comment by Lyeed** [comment]
There are none company at the server beginning.
Players have, as you said, to farm resources to build their own company.
If they cannot farm because none company has been build yet, you can force build a company as I explained to you in my previous message.
I didn't understand well your last sentence, what do you mean by "resources are not shown"  ?

**Comment by Lyeed** [comment]
These icons are created after the construction process.
If not do you included the whole pack-mods I provided in the readme ?

**Comment by CHL198011** [comment]
Je ne comprends pas très bien ce que vous voulez dire, j'ai utilisé la version 1.1, je l'ai traduite par souci de commodité, je ne sais pas si elle a corrompu le code

**Comment by Lyeed** [comment]
Maybe you made a mistake during the traduction :/
People have been using my framework and none issue has been open concerning map icons
