### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by psika26** [Lyeed/Framework_Tanoa_Life#28]
Bonjour, 
J'aurais juste 2 petites questions : 

1. Savez vous comment fonctionne le siphon pour vider un réservoir et le changer 
2. Comment configure ton le paiement à une entreprise lorsque celle-ci ravitaille les pompes. 

Merci d'avance pour votre aide.

**Comment by Lyeed** [comment]
Bonjour,

Tu peux trouver les interactions avec un véhicule [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Game/Interactions/fn_interactions_player_to_vehicle.sqf)

Pour accéder à l'action il faut remplir la condition.
Par exemple concernant le siphon la voici :
````
((vehicle player) isEqualTo player)	&&
('Alysia_siphon' in (magazines player)) &&
(['company_garagist'] call AlysiaClient_fnc_hasLicense)
````

Concernant le ravitaillement des pompes tu peux trouver la formule de calcul dans [ce fichier](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Game/FuelStations/fn_fuelStation_stock_progress.sqf) ligne 74
