### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MuTicax** [Lyeed/Framework_Tanoa_Life#29]
Bonjour l'hotel des ventes est t'il diponible sur cette version ? Et il y a t'il possibilite de vendre des vehcule de joueur a joueur

**Comment by Lyeed** [comment]
Bonjour,

L’hotel des ventes n’est pas dans cette version. Il était présent dans la version de Sibranak mais n’était pas fiable.
Concernant l’échange de véhicules entre particuliers, il ne me semble pas que la fonctionnalité ait été faite. Tu peux vérifier s’il existe une option dans le menu d’echange pour donner définitivement ses clefs mais je ne pense pas

**Comment by MuTicax** [comment]
Non malheuresement on peut que echanger pour un reeboot
