### ISSUE TITLE
Aide à la configuration

### ISSUE THREAD

**Issue by RtcSmocky** [Lyeed/Framework_Tanoa_Life#3]
Salut,

Tout d'abord je tiens à te remercier pour ce partage.
Serait-il possible de faire un mini tuto pour le lancement de ta mission sur un serveur ?
J'ai essayé comme j'ai l'habitude de faire mais ça ne fonctionne pas.

Merci d'avance :)

**Comment by boubablackmamba** [comment]
Bonsoir je viens à vous, car je but cela fais trois jours avec un écran noir en attente de réponse du serveur.J'ai suivis le tuto à la lettre je ne suis pas une flèche, je ne sais pas si j'ai bien fais ou non.

Voici mon pastebin
https://pastebin.com/A9x8Tdt8
et je n'arrive pas a savoir d'ou est l'erreur suivante:
Warning Message: Script Tanoa-Server\fn_initServer.sqf not found

Cordialement, dans l'attente d'une réponse de votre part.

**Comment by Lyeed** [comment]
@boubablackmamba 
Merci de faire un message de ton côté

@RtcSmocky 
Qu'est ce qui ne fonctionne pas ? Tu as assez d'information dans le README pour pouvoir démarrer ton serveur avec le framework

**Comment by RtcSmocky** [comment]
Déjà dès le lancement d'arma3server j'ai le droit à
`ErrorMessage: File , line 1: Config: End of line encountered after Tanoa-Server`

Juste savoir comment mettre en place tes fichiers dans le dossier Arma3server et les paramètres de lancement.

**Comment by RtcSmocky** [comment]
J'utilises actuellement la dernière release en date.

J'ai mis le modpack @Alysia en place, je crée un dossier @Tanoa-Server avec dedans un dossier addons ou je mets le dossier Tanoa-Server en .pbo, j'ai mis en @ExtDB2 et configuré le .ini, j'ai mis en place en à la racine du dossier Arma3Server ExtLog, je mets le dossier Tanoa-Life.Tanoa en .pbo dans le dossier mpmissions.

Depuis TADST j'ai
`-mod=@Alysia;@extDB2;@Tanoa-Server`
Et Tanoa-Life.Tanoa.pbo en mission.

Est-ce le bon fonctionnement ou je me suis loupé quelque part ?

**Comment by Lyeed** [comment]
Vérifies que tu n'ais pas un retour à la ligne dans le fichier $PREFIX$ du serveur.
Si tu en a un supprime le de sorte à ce que la première ligne n'ai pas de retour à la ligne.
N'oublie pas de rebuild ensuite le serveur.

**Comment by RtcSmocky** [comment]
Effectivement le soucis venait de là.
Merci :)

**Comment by Lyeed** [comment]
De rien

**Comment by KillianDubois** [comment]
J'ai le même problème que lui mais même si j'ai vérifier tout tout tout je reste avoir les problème. Faut-il un emplacement spécifique du mot de passe rcon? Car la je l'ai A3Master/ServerProfiles/BattlEye
