### ISSUE TITLE
Quelque Question

### ISSUE THREAD

**Issue by Loic24** [Lyeed/Framework_Tanoa_Life#30]
Bonjour/Bonsoir Lyeed. Je me permet de t'envoyer ce message car nous avons pris ton framework tonoa life mais nous l'avons modifié et mis sur malden , j'ai pu reglé certaine chose mais j'aimerais savoir comment faire pour connaitre et remettre les position de point de drogue etc etc Merci.

**Comment by Lyeed** [comment]
Bonjour,

Tu peux retrouver les positions dans le fichier Config_server.hpp qui se trouve dans le pbo du serveur

**Comment by Loic24** [comment]
Et Petite explication pour refaire ceci comment est-ce que je doit procéder ? Sauriez vous m'expliquer car je suis un peut bloqué Merci d'avoir répondu Lyeed

**Comment by Lyeed** [comment]
Il s'agit de tableaux de positions AGL d'Arma.
Pour en ajouter des nouvelles tu peux récupérer ta position actuelle avec `getpos player`
