### ISSUE TITLE
Question concernant le rangement automatique des véhicules 

### ISSUE THREAD

**Issue by psika26** [Lyeed/Framework_Tanoa_Life#31]
Bonjour, 
Je souhaiterais pouvoir augmenter le temps avant qu'un véhicule soit ranger automatiquement dans le garage j'ai trouvé ce fichier : core\Cleanups\fn_cleanup_vehicles.sqf 

Pouvez-vous m'aiguiller svp ? 
Merci

**Comment by Lyeed** [comment]
Bonjour,

Il est possible de modifier le temps avant qu'un véhiule ne soit rangé à partir de [ce fichier](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Server/core/Cleanups/fn_cleanup_vehicles.sqf)

- Ligne 15 : remplacer 6 par le chiffre voulu. A savoir que 6 représente 60 minutes
- Ligne 27: remplacer 5 par votre nouvelle valeur - 1. Cela permet de prévenir le joueur que son véhicule sera mis en fourrière dans 10 minutes (d'ou le - 1)

Cela doit suffire pour modifier le temps.
