### ISSUE TITLE
Skin alysia

### ISSUE THREAD

**Issue by thomas62340** [Lyeed/Framework_Tanoa_Life#34]
Salut à toi il es ou le skin des nouveaux le tee shirt alysia dans les addons 
et c'est quelle fichier pour modifier le skin de départ

**Comment by thomas62340** [comment]
Problème réglés par contre j aimerais remettre la sirène car enfaite je fais Shift F mais la sirène ce met pas que sa sois GDM ou ANT sa fonctionne pas tu aurais une solution ?

**Comment by Lyeed** [comment]
Bonjour,

Je clos le ticket, si le problème de sirène est toujours présent faites un nouveau ticket associé au soucis et on verra pour le résoudre :+1:
