### ISSUE TITLE
Instalation fichiers serveur

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#35]
Bonjour,

J'ai récupéré les fichiers que vous partager et j'aimerai les installer sur mon serveur.

Vos fichiers de mission sont ils fait par rapport à la version de TONIC ou l'avait vous refait entièrement vous même ?

J'aimerais également savoir comment l'installer sur mon serveur life (installer les fichiers de mission, et comment configurer le extDB3)

Merci de votre aide

Cdt

**Comment by Lyeed** [comment]
Bonjour,

La mission n'a rien à voir avec Altis Life de Tonic.
Concernant la configuration du serveur il y a un readme a la racine du projet GitHub
https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/README.md
