### ISSUE TITLE
Je suis la personne qui t'a demandé de l'aide sur altis dev

### ISSUE THREAD

**Issue by Homiris** [Lyeed/Framework_Tanoa_Life#37]
MERCI POUR TA RÉPONSE JAIS INSTALLER CORRECTEMENT MAIS DANS LE LOBBY JAIS UN MSG NO entry ‘bin\config.bin/CfgMarkers.Maels_hospital’ et je c’est pas du tous cela veux dire stp merci

**Comment by Lyeed** [comment]
Vérifies que tu ais bien inclus les mods côté client et serveur

**Comment by Homiris** [comment]
Ba les modes apart @alysia pour côté client je vois quoi mettre de plus côté client il y aurai quoi comme @mod à mettre côté client et côté serveur ? Voir si jais bon ou pas. Merci

**Comment by Lyeed** [comment]
Le serveur doit avoir les memes mods que le client ainsi que Tanoa-Server en plus.
Pour les mods ce sont ceux dans le .rar que tu peux télécharger dans le README

**Comment by Homiris** [comment]
Don à se que jais compris côté client il fais aussi en plus du mod alysia le mod @tanoa server?

**Comment by Homiris** [comment]
Après je suis chez nitrado juste voir comment installer le serveur es que sa un problème ?

**Comment by Homiris** [comment]
Ba écoute je recommence tout à zéro et je te tien au jus sa marche.

**Comment by mecta02** [comment]
@Homiris Attention car l'arborescence de l'addon ma déjà tromper je mexplique 

si tu fait extraire ici âpres avoir télécharger il recrée un fichier @alysia
se qui done @alysia--@alysia--addons
tu a juste a couper le addons et le mettre dans le fichier @alysia de base 

je ne ces pas si ces explicite

**Comment by Homiris** [comment]
Merci pour votre aides mais je mes suis mis en version extdb2 et cela fonctionne

**Comment by Lyeed** [comment]
Je ne pense pas que ton problème soit lié à extdb.
Si tu souhaites revenir vers extdb3 et nous founir des logs pour qu'on puisse t'aider, fait signe.

**Comment by Homiris** [comment]
Merci @Lyeed c'est bon jais fixé comment et en 5.0 extdb3 merci comme même .
