### ISSUE TITLE
haut les mains 

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#38]
Bonjour j'ai un petit souci quand on fait alt+t pour lever les mains nickel mais impossible de les baisser :-(

une idée une piste ? 

merci

**Comment by Lyeed** [comment]
Bonjour,

La touche pour lever et baisser les mains est ALT+H par défaut si vous n'avez rien changé.
Si vous l'avez effectivement changé il est possible que plusieurs actions soient liées à ALT+T et empêche donc de les baisser.

**Comment by mecta02** [comment]
désoler erreur de saisie ces bien Alt+H il mais donc les mains sur la tete  mais quand on veut les enlever sa dit que lon ne peut effectuer cette action avec les main sur la tete - le framework na pas étai modifier

**Comment by mecta02** [comment]
seul point a regler pour open la beta ;-(

**Comment by mecta02** [comment]
*fix
modif de la ligne 
if (player getVariable ["surrender", true]) exitWith 

pas d'impact sur le blocage des actions en ayant les mains sur la tete .
resoud mon problème de message interdisant les action en ayant les mains lever .

**Comment by mecta02** [comment]
en revanche si tu peut expliquer comment afficher la console de debug en jeux stp se serai cool

**Comment by Lyeed** [comment]
Tu aurais pu trouver cette information sur internet
https://community.bistudio.com/wiki/diag_log

Ton problème n'a cependant pas été reporté par d'autres serveurs utilisant le framework

**Comment by Lyeed** [comment]
Je ferme le ticket sans nouvelle concernant cet étrange soucis.
