### ISSUE TITLE
Lien  Addons avec fichier de mission. 

### ISSUE THREAD

**Issue by Homiris** [Lyeed/Framework_Tanoa_Life#39]
Bonjour étend donner que vous partagez vos fichier de mission et l'addons Alysia, je voulais savoir sont il libre d'accès sens avoir de souci à l'ouverture de notre serveur? Cdt

**Comment by Lyeed** [comment]
Bonjour,

Vous pouvez utiliser ce qui a été partagé dans la limite de la licence.
Si votre question concerne les mods, ils sont partagés avec la mission et ne peuvent être utilisés séparément.

**Comment by Homiris** [comment]
Bien merci mais ai-je le droit de modifié juste le nom du mod je parle bien de celui la @alysia ?

**Comment by Lyeed** [comment]
Oui tu peux modifier le nom du mod qui contient les addons
