### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#4]
Bonjour je viens a vous car j'ai un souci d'installation je doit mal faire  quelque part avez vous 2 min a m'accordez sur teamspeak svp on va dire je fais de mon mieux je ne suis pas une fleche.

**Comment by boubablackmamba** [comment]
Bonjour et dsl de mon indelicatesse
dite moi le Tanoa server va bien dans le life serv en .pbo?
serconde question je pense bloquer au niveau d'ici 
Server Addons Configurations Link

Line 123 : Add in the array your server's addons cfgpatches
Exemple : if (!(_pbo in ["TanoaServer","asm","myNewAddon"])) then {

⚠️ You must add the addon's cfgpatch and not the addon's folder name. Check out this information in your addon's config file

Author
J'ai du mal a comprendre il faut mettre quoi dedant? cordialement ne m'en voulez pas jessais de comprendre au mieux et j'essais de progresser.

**Comment by Lyeed** [comment]
Tu peux mettre @BoubaServer @MonServer @LifeServer ainsi de suite. Ce dossier doit contenir un dossier addons. Dans ce dossier addons tu dois mettre le pbo TanoaServer. Le serveur doit être démarrer avec l'extension @ que tu as crées.

Et concernant ta deuxième question tu ne dois modifier cette ligne que si tu souhaites rajouter des pbo en plus côté serveur. Si tu ne souhaites que lancer le framekwork tu n'as pas à toucher à cette ligne.

**Comment by boubablackmamba** [comment]
Lorsque je met le tanoa-server en pbo j'ai ce message

12:24:11 ErrorMessage: File , line 1: Config: End of line encountered after Tanoa-Server
12:24:11 Application terminated intentionally
ErrorMessage: File , line 1: Config: End of line encountered after Tanoa-Server

j'ai pu constater que cela venais du prefix et si je supprime le prefix ecran noir dans l'attente de réponse du server. dsl jessais de m'appliquer

**Comment by Lyeed** [comment]
Merci de te référer à cette issue pour trouver la solution de ton problème.
https://github.com/Lyeed/Framework_Tanoa_Life/issues/3
