### ISSUE TITLE
chez papy leon

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#40]
salu salu salu 

je souhaite me debarasser du bar papy leon qu comment faire svp il n'est pas présent dans le mission sqm . merci de l'aide 
bisous bisous

**Comment by mecta02** [comment]
*fix 
merci quand mème pour ton taf

**Comment by Lyeed** [comment]
Une partie du mapping se retrouve dans [init_buildings](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Inits/fn_init_buildings.sqf)
