### ISSUE TITLE
Mettre plusieurs uid dans le config-staff.hpp

### ISSUE THREAD

**Issue by Homiris** [Lyeed/Framework_Tanoa_Life#41]
Bonjour je me permets de vous demander comment mettra plusieurs uid dans le fichier Config-Staff.hpp
merci CDT

#define ADMIN_AND_MODO {"XXXXXXXXXXXXXXXXXX","XXXXXXXXXXXXXXXXXX"} //la j'ais compris <-----------------

class ALYSIA_STAFF
{
	class ranks
	{
		class admin {
			name="Administrateur";
		};
		class modo {
			name="Modérateur";
		};
		class support {
			name="Support";
		};
	};

	class members
	{
		// - Admin
		class admin
		{
			rank="admin";
			teamspeak=1;
			slot=1;
			skip_checks=1;
		};
		class MyAdminName: admin
		{
			uid="XXXXXXXXXXXXXXXXXX"; <---------------mais la
		};

		// - Modo
		class modo
		{
			rank="modo";
			teamspeak=1;
			slot=1;
			skip_checks=1;
		};
		class MyModoName: modo
		{
			uid="XXXXXXXXXXXXXXXXXX";
		};

		// - Support
		class support
		{
			rank="support";
			teamspeak=1;
			slot=0;
			skip_checks=0;
		};
		class MySupportName: support
		{
			uid="XXXXXXXXXXXXXXXXXX";
		};
	};

**Comment by mecta02** [comment]
ta du mal quand méme ... turecrée une class sous la classe 
lenomquetuveut: admin
{
             uid="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
};

**Comment by Homiris** [comment]
ok merci.

**Comment by Lyeed** [comment]
Comme l'a précisé @mecta02 tu dois effectivement créer une classe par uid, héritant chacune du role que tu souhaite leur attribuer.
