### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#42]
Bonjour, j'aimerai savoir dans quel fichiers se trouvent les prix des vêtements, vehicules etc..
J'aime également savoir comme créer une entreprise.

Merci

Cdt

**Comment by mecta02** [comment]
si tu ne te donne pas la peine de chercher remai en doute ta possibilité administrée un server !!

si tu avais chercher un peut tu aurai vu que dans la mission il ya config/gameconfig et la magie il ya tous se que tu recherche

**Comment by HKaoTic** [comment]
Malheuresement, il n'y a pas le init pour la création des entreprises.
Merci pour ta magnifique réponse avec une politesse inéxistante.
Si je demande, c'est que je n'ai pas trouvé, tu devrait également réfléchir.
Ici on est pas chez AltisDev.

Cdt

**Comment by Lyeed** [comment]
Tout ce qui permet de créer des nouveaux élements ou de modifier des existants se trouve dans le dossier précisé par @mecta02 

Pour ajouter un nouveau type d'entreprise par exemple, tu dois modifier le fichier de config des entreprises.

**Comment by HKaoTic** [comment]
@Lyeed Lyeed, merci de ta comfirmation.

Je voulais savoir comment créer une entreprise EN JEU.
Car je ne trouve pas le panneau pour...

Cdt

**Comment by Lyeed** [comment]
Ah en jeu, tu dois posséder la licence de création d'entreprise précisée dans config_factions
La personne qui possède la licence doit ensuite faire windows (menu interaction) sur le PDG de la nouvelle société. Une option de création d'entreprise sera visible

**Comment by HKaoTic** [comment]
Comment peut on obtenir les licences nécessaires pour la création des entreprises ?
Quel PDG ? Est ce un joueur ?

**Comment by Lyeed** [comment]
Oui le PDG est un joueur.
Dans la config par défaut, pour la faction civile, la licence qui permet de créer des entreprises est "coop_agri"
Tu peux retrouver ces conditions [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Factions.hpp)

**Comment by HKaoTic** [comment]
Daccord, merci de l'aide.

Nous devons definir le PDG via la DB ? si non, apr ou devons nous le définir ?

**Comment by Lyeed** [comment]
Le PDG est de facto la personne qui est la cible lors de la création d'une entreprise. Il n'y a pas d'interaction avec la db a faire, à moins que tu veilles donner la licence coop_agri directement à la personne qui s'occupe de la création d'entreprises.

Les laboratories de traitement doivent être achetés au marché noir et montés avec des matériaux à l'emplacement souhaité

**Comment by HKaoTic** [comment]
Je n'ai pas vraiment tout compris concernant la création d'entreprise..

Il faut un plan de construction pour les construires ?
Quel matériaux ?
Peut on directement les rajouter sur la map ?

**Comment by Lyeed** [comment]
Tout se fait en jeu. Donne toi la licence coop_agri, fais windows sur un joueur de la faction civil et découvre le systeme d'entreprise par toi même

**Comment by HKaoTic** [comment]
Pour les laboratoires

Il faut un plan de construction pour les construires ?
Quel matériaux ?
Peut on directement les rajouter sur la map ?

**Comment by Lyeed** [comment]
Pour les laboratoires tu dois acheter un item que tu déplois et doit construire. Tu peux les acheter au marché noir (que le joueur doit trouver, tu peux en soit avoir la position directement dans la db)

**Comment by HKaoTic** [comment]
Peut on directement les rajouter sur la map ?

**Comment by Lyeed** [comment]
Ah oui c'est au marché rebelle par défaut les laboratoires.
Il faut que tu apprennes à lire et utiliser la config de la mission sinon tu n'arriveras pas à modifier ou utiliser le framework.

Fichier des shops des items virtuels : https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Shop_Virtual.hpp

**Comment by HKaoTic** [comment]
Peut on directement les rajouter sur la map ? (Editeur)

**Comment by Lyeed** [comment]
Non tu ne peux pas

**Comment by HKaoTic** [comment]
Daccord

Merci de votre aide
