### ISSUE TITLE
station service 

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#43]
Bonjour le joueur qui s’occupe du carburant me demande de faire en sorte que les station ne se remplisse pas a 100% au reboot chaque jour quelle valeur modifier pour cela ? 

merci  :-)

**Comment by Lyeed** [comment]
Les stations ne se remplissent normalement pas au reboot. Leur stock est sauvegardé.
Il se peut que tu ais une erreur et que la save ne se fasse pas.
Regarde dans ton log d'une sauvegarde au moment d'un reboot et dis moi si tu trouves la sauvegarde des pompes.

**Comment by mecta02** [comment]
ces good probléme regler :-)
