### ISSUE TITLE
homming

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#44]
Bonjour je cherche a ajouter la homming" la personnalisation de linterieur des maisons" j'ai réussi en utilisant le méthode des laboratoires le seul point qui me dérange ces le fait que forcement ces item sont considérer comme des labos est on donc un espace destockage est aucune interraction pour les chaises par exemple j'ai passer 3heures a lire le code est a essayer de recrée les donnée pour avoir une fonction différentes mais je patoge pas mal sur se coup si je te fournis les modif effectuer est tu disponible non pas pour me dire les solution" on apprend pas comme sa "  mai juste pour me dire si il manque des infos est la ou je fait des erreurs biensur une foi fini tu peut l’ajouter a ta mission ou je peut le proposer en complément 

merci

**Comment by Lyeed** [comment]
Il n'est pas vraiment possible d'utiliser le systeme de laboratoire pour le housing sans faire pas mal de modifications puisqu'il contient plusieurs conditions et fonctionnalités spécifiques à un laboratoire de drogue.
- Le nombre de laboratoire que peux poser une personne
- Le fait que l'armée peut le détruire...

**Comment by mecta02** [comment]
okok je part sur un autre système alor j’essaye avec le principe utiliser pour la tour de guet etc
