### ISSUE TITLE
Système de soin

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#45]
Bonjour, j'aimerai savoir s'il possible de changer le système de soin et de santé car pour moi la santé diminue trop rapidement et l'on meurt trop facilement.

Merci.

**Comment by Lyeed** [comment]
Bonjour,

Si tu souhaites changer le systeme tu es libre de modifier la mission.
Si tu trouves que les joueurs meurent trop facilement tu peux modifier les variables dans le fichier de config du systeme médicale ou directement à partir de l'evenement handledamage
