### ISSUE TITLE
compte entreprise 

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#46]
RE Salut

J'ai commencer avec les joueurs a regarder les entreprises est mai une surprise étrange l'argent des comptes entreprise n'est pas save dans la db alor que tous le reste est biens sauvegarder .
:-( si je siasie la somme dans la db server etein et que je le rallume la ces ok donc ces uniquement un probléme de sauvegarde

**Comment by Lyeed** [comment]
Si c'est un soucis de sauvegarde, vérifie tes logs serveur au moment du reboot.
Tu dois avoir des erreurs qui empêche l'execution de la sauvegarde

**Comment by mecta02** [comment]
effectivement probléme regler causer par moi :-(
