### ISSUE TITLE
class central_plate 

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#47]
quand un joueur west envoi un message au central afin d’identifier le propriétaire d'un véhicule il reçoi un message d’erreur " aucun véhicule ne correspond a votre demande .

cette fonction est t'elle fonctionnel ou reste t'elle a développer??

merci

**Comment by mecta02** [comment]
corriger il faut que le joueur soi co ou le vehicule sorti je pense

**Comment by mecta02** [comment]
quelel serai la modif a apporter pour l'assurance svp

**Comment by Lyeed** [comment]
Etant donné que c'est une assurance de véhicule il faut aller voir dans la config liée aux véhicules.
