### ISSUE TITLE
doG

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#48]
Bonjour je n'arrive pas a recuperer le chiens malgré la licences  .sur le panneau je n'est pas de menu permetan cette action je suis bien au niveau 11 pour l'ant

**Comment by Lyeed** [comment]
Bonjour,

Tu as été voir dans le sqm la condition pour afficher le menu ?

**Comment by mecta02** [comment]
une histoire de distance d'un vehicule ces biens sa ?

**Comment by Lyeed** [comment]
Je ne sais plus où l'on accède à ce menu.
Il me semble que tu peux récupérer un chien à partir du panneau de la base militaire. Si tu ne vois pas donc pas l'action, regarde dans le panneau quel est la condition pour ouvrir le menu que tu cherches.

**Comment by mecta02** [comment]
init="call{this enableSimulation false;this allowDamage false;this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\shop.paa'/> Supérette"",AlysiaClient_fnc_shop_virtual_open,""east"",0,false,false,"""",'vehicle player == player && player distance _target < 4'];this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\gun.paa'/> Armurerie"",AlysiaClient_fnc_shop_arma_open,""EAST_gun"",0,false,false,"""",'vehicle player == player && player distance _target < 4'];this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\shop.paa'/> Friperie"",AlysiaClient_fnc_shop_clothing_open,""EAST_clothing"",0,false,false,"""",'vehicle player == player && player distance _target < 4'];this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\shop_car.paa'/> Concessionnaire"",AlysiaClient_fnc_shop_vehicles_open,[""EAST"",[]],0,false,false,"""",'vehicle player == player && player distance _target < 4'];this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\shop.paa'/> Commander des <t color='#FFBF00'>convois</t>"",AlysiaClient_fnc_shop_mission_open,"""",0,false,false,"""",'vehicle player == player && player distance _target < 4'];this addAction[""<img image='Alysia_Client_Texture\Data\actions_menu\shop.paa'/> Récupérer un <t color='#FFBF00'>chien</t>"",AlysiaClient_fnc_dog_get,"""",0,false,false,"""",'vehicle player == player && player distance _target < 4 && (isNull g_dog) && ([""east_dog""] call AlysiaClient_fnc_hasLicense)'];}";

**Comment by mecta02** [comment]
sayer resolu dsl du derangement

**Comment by Lyeed** [comment]
Quand tu as une interrogation ou un soucis essaye d'abord de chercher par toi même, tu aurais quand même pu trouver la solution tout seul pour ce cas la.
