### ISSUE TITLE
Problème démarrage du serveur

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#49]
Bonjour, une fois tout installer, je veux démarrer le serveur et lorsque la mission est chargée, s'affiche "En attente de réponse du serveur..."

Fichier : initPlayerLocal.sqf

Je ne vois pas d'où ça vient et comment régler se problème.

Merci d'avance pour votre aide

Cdt

**Comment by Lyeed** [comment]
Bonjour,

Regarde dans le log de ton serveur, tu dois avoir des erreurs.
