### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#5]
Re bonjour j'ai corriger les erreurs c'etais du au retour a la ligne du prefix  le serveur ce lance toujours ecran noir en attente du serveur et ceci Failed attempt to execute serverCommand '#lock' by server. 
 cordialement

**Comment by Lyeed** [comment]
Pour l'erreur concernant le verrouillage du server, tu as du mettre le mauvais mot de passe rcon dans la config du serveur. Tu as des informations la dessus dans le readme.

Concernant l'écran noir tu dois avoir des informations dans les logs du serveur pour t'expliquer sa provenance.

**Comment by boubablackmamba** [comment]
Probleme regler extdb2.dll manquant.
Dite moi si je change de map sur quel fichier il y a des changement a faire et comment faire pour enlever sur le logo alysia ainsi que la tablette cordialement

**Comment by boubablackmamba** [comment]
Bonjour j'aimerais savoir si je Change de map si dans un fichier je doit changer les coordonées.
Deuxieme question peut-on enlever le mot alysia partout dans la tablette et sur les logos?
Cordialement

**Comment by Lyeed** [comment]
Si tu changes de cartes il faut changer le mission.sqm et les coordonnées dans la configuration du serveur.

Concernant ta deuxième question tu peux changers les assets (images/sons/textures) des pbo si tu le souhaites.

**Comment by Lyeed** [comment]
Le problème d'installation étant résolu, je ferme le ticket
