### ISSUE TITLE
Problème licence entreprise. 

### ISSUE THREAD

**Issue by Homiris** [Lyeed/Framework_Tanoa_Life#50]
Bonsoir, après plusieurs tentative et de recherche, nous pouvons crée une entreprise et donc au reboot l'entreprise et la mais pas de licence pour le joueur limite disparue . 
cdt.

**Comment by Lyeed** [comment]
Bonjour,

Si vous rencontrez des soucis de rollback vérifiez que le serveur s'éteint et se redémarre correctement à chaquer reboot. Si vous sautez la phase de sauvegarde qui est 2 à 3 minutes avant le redémarrage, il vous perdrez plein de données.

**Comment by Homiris** [comment]
Bonsoir donc j'ais bien toute les licences mais celle pour les entreprise elle , elle saute au reboot.
CDT.

**Comment by Lyeed** [comment]
Si tu perds des licences c'est qu'une sauvegarde de ton personnage ne se fait pas ou que tu es. As-tu des soucis de crash ou de déconnexion ?

**Comment by Homiris** [comment]
ba jais que la licence company qui save pas, mais les autre oui c'est save . dsl du dérangement.
cdt.

**Comment by Homiris** [comment]
non pas souci de crash ni de déconnection.

**Comment by Homiris** [comment]
17:32:34 "-------------------------------------------------------------"
17:32:34 "-------------------- Starting Server Init -------------------"
17:32:34 "-------------------------------------------------------------"
17:32:34 "extDB3: Version: 1.028"
17:32:34 "extDB3: Connected to Database"
17:32:34 "extDB3: Initalized SQL_CUSTOM Protocol"
17:32:34 "extDB3: Locked"
17:32:34 "[DYNAMIC MARKERS] Initializing"
17:32:34 Attempt to override final function - bis_fnc_storeparamsvalues_data
17:32:34 "Creating dynamic marker cocaine_field_marker_1"
17:32:34 " :: [RCON:ALL-KICK] Loop begin ::"
17:32:34 " :: [RCON:ALL-KICK] Loop end ::"
17:32:34 Failed attempt to execute serverCommand '#lock' by server.
17:32:34 "Creating dynamic marker cannabis_field_marker_1"
17:32:34 "Creating dynamic marker meth_field_marker_1"
17:32:34 "arma3/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 24375 ms -----"
17:32:34 "Creating dynamic marker heroin_field_marker_1"
17:32:34 "Creating dynamic marker mushroom_field_marker_1"
17:32:34 "Creating dynamic marker launder_marker_1"
17:32:34 "Linked object for launder_marker_1 placed"
17:32:35 "Creating dynamic marker blackMarket_marker_1"
17:32:35 "Linked object for blackMarket_marker_1 placed"
17:32:35 "extDB3: uisleep [4]: 76.718"
17:32:35 "Creating dynamic marker blackMarket_marker_2"
17:32:35 "Linked object for blackMarket_marker_2 placed"
17:32:35 "Creating dynamic marker cars_seller_marker_1"
17:32:35 "Linked object for cars_seller_marker_1 placed"
17:32:35 "Creating dynamic marker cars_seller_marker_2"
17:32:35 "Linked object for cars_seller_marker_2 placed"
17:32:35 "Creating dynamic marker drugs_seller_marker_1"
17:32:35 "Linked object for drugs_seller_marker_1 placed"
17:32:35 "Creating dynamic marker drugs_seller_marker_2"
17:32:35 "Linked object for drugs_seller_marker_2 placed"
17:32:35 "Creating dynamic marker archeologie_field_marker_1"
17:32:35 "Creating dynamic marker renovation_marker"
17:32:35 "Linked object for renovation_marker placed"
17:32:35 "Creating dynamic marker pillage_field_marker_1"
17:32:35 "Creating dynamic marker soufre_process_marker_1"
17:32:35 "Linked object for soufre_process_marker_1 placed"
17:32:35 "Creating dynamic marker rebel_marker_1"
17:32:35 "Linked object for rebel_marker_1 placed"
17:32:35 [12709,45.1977,77.107,0.604,[5140488b80# 1696133: campfire_f.p3d],"Campfire_burning_F",[5802.27,13033.9,11.1091]]
17:32:35 "Creating dynamic marker rebel_marker_2"
17:32:35 "Linked object for rebel_marker_2 placed"
17:32:35 [12713,42.5532,77.209,0.712,[5166943580# 1696134: campfire_f.p3d],"Campfire_burning_F",[11164.2,14529.8,15.6295]]
17:32:35 "Creating dynamic marker corail_field_marker_1"
17:32:35 "[DYNAMIC MARKERS] Ready"
17:32:35 "[PHONE] Setup"
17:32:36 "[PHONE] Ready"
17:32:36 "[LABORATORIES] Setup"
17:32:37 "0 laboratory(s) loaded"
17:32:37 "[LABORATORIES] Ready"
17:32:37 "[VEHICLES] Loading"
17:32:38 "[VEHICLES] Ready"
17:32:38 "[BOURSE] Setup"
17:32:39 "[BOURSE] Ready"
17:32:39 "[HOUSE] Setup"
17:32:39 "[BOURSE] Starting market loop..."
17:32:40 "2 house(s) loaded succefully"
17:32:40 "0 house(s) failed"
17:32:40 "[HOUSE] Ready"
17:32:40 "[FACTION] Setup"
17:32:40 "Faction CIV | Bank=0"
17:32:40 "Faction EAST | Bank=0"
17:32:40 "Faction GUER | Bank=0"
17:32:40 "Faction WEST | Bank=0"
17:32:40 "[FACTION] Ready"
17:32:40 "[BUILDINGS] Init"
17:32:40 "[BUILDINGS] Ready"
17:32:40 "[COMPANIES] Setup"
17:32:40 "Company [545] | Type [construction] | Owner [J'ai masquer uid!!!] | Bank [0]"
17:32:40 "1 companie(s) loaded"
17:32:40 "[COMPANIES] Ready"
17:32:40 "[ATM] Setup"
17:32:40 a3\structures_f_exp\signs\companies\cornerads_01_v2_f.p3d: No geometry and no visual shape
17:32:41 "[ATM] Ready"
17:32:41 "[TAXES] Setup"
17:32:41 "Loading taxe [Taxe foncière] : 20%"
17:32:41 "Loading taxe [Taxe salariale] : 30%"
17:32:41 "Loading taxe [Taxe d'habitation] : 20%"
17:32:41 "Loading taxe [Cotisation salariale] : 20%"
17:32:41 "[TAXES] Ready"
17:32:41 "[FUEL STATIONS] Loading ..."
17:32:41 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:45 Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
17:32:48 Strange convex component16 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
17:32:48 Strange convex component25 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
17:32:48 Strange convex component26 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
17:32:48 Strange convex component27 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
17:32:49 BEServer::finishDestroyPlayer(1427664558): users.get failed
17:32:49 "[FUEL STATIONS] Fuel Stations Ready"
17:32:49 "[TIME] Setup"
17:32:49 "Date : 6 Avril 2019"
17:32:49 "[TIME] Ready"
17:32:49 "[CLEANUP] Setup"
17:32:49 "[CLEANUP] Ready"
17:32:49 "Prochain redémarrage à 20:00 (~ 148 minutes)."
17:32:49 "Il est 17:32"
17:32:49 "---------------------------------------------------------------------------------------------------------"
17:32:49 "Total Execution Time 14.799 seconds"
17:32:49 "---------------------------------------------------------------------------------------------------------"
17:32:49 Failed attempt to execute serverCommand '#unlock' by server.
17:34:01 BEServer: registering a new player #1502469745
17:34:10 Server: Object 0:0 not found (message Type_181)
17:34:10 Server: Object 0:0 not found (message Type_181)
17:34:13 Unaccessible
17:34:13 a3\weapons_f\binocular\nvg_proxy.p3d: No geometry and no visual shape
17:34:13 a3\characters_f_beta\heads\glasses\g_shades_red.p3d: No geometry and no visual shape
17:34:14 [16829,45.584,175.702,91.18,[CIV_1],"Skyline_Man_Alysia_01_F",[1207.44,586.8,8.08043]]
17:34:15 a3\characters_f_gamma\heads\glasses\g_aviators.p3d: No geometry and no visual shape
17:38:24 Client: Remote object 4:0 not found
17:38:24 "arma3/BIS_fnc_log: HandleDisconnect : CIV_1"
17:38:28 Warning: Cleanup player - person 2:841 not found
17:38:53 Server: Object 0:0 not found (message Type_181)
17:38:53 Server: Object 0:0 not found (message Type_181)
17:38:55 Unaccessible
17:38:55 [29692,45.7143,457.208,372.735,[CIV_1],"Skyline_Man_Alysia_01_F",[1207.44,586.8,8.08043]]
17:39:33 "arma3/BIS_fnc_log: HandleDisconnect : CIV_1"
17:39:34 Warning: Cleanup player - person 2:846 not found
17:39:35 Warning: Cleanup player - person 2:846 not found
17:40:43 BEServer: registering a new player #1903952574
17:40:51 Server: Object 0:0 not found (message Type_181)
17:40:51 Server: Object 0:0 not found (message Type_181)
17:40:54 Unaccessible
17:40:54 [35117,45.4545,576.375,491.67,[CIV_1],"Skyline_Man_Alysia_01_F",[1207.44,586.8,8.08043]]
17:45:54 Client: Remote object 5:0 not found
17:45:54 "arma3/BIS_fnc_log: HandleDisconnect : CIV_1"
17:45:55 Warning: Cleanup player - person 2:850 not found
17:45:58 Warning: Cleanup player - person 2:850 not found




Voila apres RPT.log au reboot mais se qui me choque c'est que la licence company qui sav pas c'est sa le seule souci sinon tous fonction.

**Comment by Lyeed** [comment]
Tu parles d'une licence personnage? Si oui cela n'a rien a voir avec le serveur

**Comment by Homiris** [comment]
ok je vais m'expliquer quand j'attribue une entreprise a un joueur jais le tas de brique sur le terrain pour allez plus vite je le construit avec l'admin menu la le joueur a la licence mais de que le serv reboot la licence il ne la plus . je parle que de la licence entreprise. les autre licnence c'est save.

j'espère que je me suis bien exprimer.

**Comment by Lyeed** [comment]
Le fait que le joueur perde sa licence n'est pas lié au reboot mais au joueur qui doit mal deconnecter. (sans passer par echap -> quitter)
Pour récupérer de nouveau la licence le PDG de l'entreprise peut normalement passer par la tablette pour redonner une licence non ? 
Le problème serait étrange s'il ne perdait que la licence d'entreprise mais je doute que cela arrive.

**Comment by Homiris** [comment]
> Le fait que le joueur perde sa licence n'est pas lié au reboot mais au joueur qui doit mal deconnecter. (sans passer par echap -> quitter)
> Pour récupérer de nouveau la licence le PDG de l'entreprise peut normalement passer par la tablette pour redonner une licence non ?
> Le problème serait étrange s'il ne perdait que la licence d'entreprise mais je doute que cela arrive.

Le premier paragraphe --- je me déconnecte en passent pas echap ->quitter

le deuxième paragraphe oui on peux donner la licence a un autre  joueur via la tablette mais au reboot les deux on aucune licence de lentreprise .

et oui c'est bien sa le problème c'est qu'il perde bien la seul licence entreprise au reboot.

**Comment by Lyeed** [comment]
Essaye de trouver une erreur SQL côté extDB ou une erreur de script côté client. Le fait qu'UNE license ne se sauvegarde pas est étrange voir impossible

**Comment by Homiris** [comment]
oui je vais regarder sa  je vais persévérer et éplucher tous sa merci a toi de nous consacrer du temp a nous aider . un grand Merci a toi Lyeed. je reviendrais ver toi si jais reussi.

**Comment by Homiris** [comment]
Bonjour, @Lyeed j'ais rectifier l'erreur,  il y avais bien un souci avec le reboot de la machin merci.

**Comment by Lyeed** [comment]
D'accord. Je me doutait bien qu'il y avait un soucis de reboot.

Je clos le ticket
