### ISSUE TITLE
Marker faction

### ISSUE THREAD

**Issue by Homiris** [Lyeed/Framework_Tanoa_Life#51]
Bonjour @Lyeed , j'ais un souci concernent les faction je te laisse regarder l'image...

![Marker](https://user-images.githubusercontent.com/47526324/56489929-b6477180-64e3-11e9-952a-de05f5457f3b.png)

J'aurais voulu savoir si je pouvez enlever cette fameuse position joueur car les civil nous vois sur la map et sa fais sa a tout les factions merci.

CDT

**Comment by Lyeed** [comment]
Bonjour,

Cela se configure avec le profil de difficulté A3 du serveur. 
https://community.bistudio.com/wiki/server.armaprofile

**Comment by Homiris** [comment]
Merci @Lyeed
