### ISSUE TITLE
Medical

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#52]
Bonjour,

J'amerai enlever le systeme médical de base, et le remplacé COMPLETEMENT par Ace mais je ne sais pas comment ni a quel fichier toucher

J'aimerai bien pas mal de précisions et une aide de votre pars

Cdt

**Comment by Lyeed** [comment]
Bonjour,

Je n'apporte de l'aide qu'aux problème lié à mon framework sinon je m'en finirais pas.
Si tu souhaites faire ce genre de modification, qui inclus des mods ou script extérieur, il va vouloir que tu mettes la main à la pâte.

Cordialement

**Comment by HKaoTic** [comment]
Daccord mais comment je peux désactiver les fichiers médicaux de ton framework ?

**Comment by Lyeed** [comment]
Tu ne peux pas "désactiver" les fichiers médicaux.
Fait une recherche sur "is_coma" ou "is_bleeding", g_blood tu auras la liste des fichiers qui utilise le système médical.
