### ISSUE TITLE
Le serveur reste en #lock

### ISSUE THREAD

**Issue by OreoFR** [Lyeed/Framework_Tanoa_Life#54]
Salut Lyeed, j'avais déjà fait fonctionner le serveur mais la, j'ai un petit souci.. Tout fonctionne niquel sauf qu'il ne fait pas le #unlock .. 

Il n'y a pas d'erreur particulière dans le RPT ( je ne l'ai pas avec moi ) j'ai pu voir un souci d'extDB3 mais je l'ai corrigé mais la je séche.. ( quand je me connecte avant que le #lock passe je suis "en attente de réponse" IG donc.. 

Si tu as un petite idée..

**Comment by Lyeed** [comment]
Bonjour,

Si le serveur se verrouille c'est pour initialiser les fonctionnalités du framework.
Une fois terminé, si tout s'est bien déroulé, le serveur se déverouille.
S'il ne se déverouille pas c'est qu'il y a donc un soucis lors de l'init.

As tu un message côté serveur qui t'indique combien de temps le serveur a mis à s'init ?

**Comment by OreoFR** [comment]
C'est bloqué ici
( le souci du extDB3 n'empechais pas l'utilisation du serveur avant.. ( il est quand même bien présent dans la racine d'arma et dans le dossier je crois )
```
"-------------------------------------------------------------"
"-------------------- Starting Server Init -------------------"
"-------------------------------------------------------------"
Call extension 'extDB3' could not be loaded: Le module spécifié est introuvable.

"extDB3: Version: "
"extDB3: Failed to Load Extension"
Attempt to override final function - bis_fnc_storeparamsvalues_data
" :: [RCON:ALL-KICK] Loop begin ::"
Successfull attempt to execute serverCommand '#lock' by server.
"sc/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 866.999 ms -----"
```

**Comment by Lyeed** [comment]
Le serveur à besoin de extdb pour communiquer avec la base de données.
Sans sa il ne peut pas finir son initialisation puisqu'il a besoin de récupérer ou de stocker des données.

Extdb semble mal installé. Pourrais-tu refaire son installation en suivant [les indications suivantes](https://bitbucket.org/torndeco/extdb3/wiki/Installation).

Egalement n'oublies pas de modifier le fichier de config extdb par la suite en suivant les consignes du README de mon répo

**Comment by OreoFR** [comment]
On est d'accord que j'ai que le @extDB3 a avoir a la racine du serveur ? car même en ayant recommencer et tout bien config j'ai toujours le même problème :/

**Comment by Lyeed** [comment]
Regarde si extdb est chargé comme addon au demarrage d'arma dans le log server

**Comment by Lyeed** [comment]
Du nouveau concernant le soucis ?

**Comment by antadrias** [comment]
j'ai le même souci que lorsque le serveur redémarre

**Comment by luxman78** [comment]
bonsoir, j'ai aussi le message d'erreur http://prntscr.com/ng75t0  lorsque je lance le serveur si je deplace le .pbo à la racide du dossier @TanoaServer le message disparrait.

**Comment by luxman78** [comment]
Bonjour,
Plus de problème avec cete version de Extdb3 :-)

https://bitbucket.org/torndeco/extdb3/downloads/extDB3-1031.7z

le server se lock au chargement du fichier mission coté pc client et se unlock ensuite

**Comment by Lyeed** [comment]
Parfait.
Pour ceux qui le même soucis, pensez à mettre à jour comme expliqué ci dessus.
