### ISSUE TITLE
Equivalent du actionKeyHandler

### ISSUE THREAD

**Issue by Oxxmo** [Lyeed/Framework_Tanoa_Life#55]
Bonjour @Lyeed ,
J'ai pas mal cherché et j'aimerias que tu m’ôte d'un doute. 
Y'a t'il un équivalent au ActionKeyHandler de Tonic dans ton framework où bien, fonctionne t il avec le CBA ? 
Cordialement.

**Comment by Lyeed** [comment]
Salut.

[Si tu cherches l'événement qui est déclenché lorsqu'un joueur appuis sur une touche](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/EventHandlers/fn_onPlayerKeyPress.sqf)
[Si tu cherches celui qui est en rapport à la touche d'interaction Windows](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/EventHandlers/fn_actionKeyHandler.sqf)

**Comment by Oxxmo** [comment]
Super Lyeed ! Merci :D

**Comment by Lyeed** [comment]
Je clos le ticket :)
