### ISSUE TITLE
Comment mettre une personne inconsciente en menottes dans une voiture

### ISSUE THREAD

**Issue by GelvineShore** [Lyeed/Framework_Tanoa_Life#56]
Salut

Si une personne est arrêtée ou est dans le coma, elle ne peut pas être mise dans une voiture. Comment le réparer?

**Comment by Lyeed** [comment]
Bonjour,

Il faut monter avec la personne dans le véhicule dans la portant.

**Comment by GelvineShore** [comment]
Merci Problème fermé
