### ISSUE TITLE
Informations 

### ISSUE THREAD

**Issue by antadrias** [Lyeed/Framework_Tanoa_Life#57]
Bonjour 👋 j’ai pu mettre correctement le serveur mais j’aurai voulu savoir comme sa se passe pour mettre en place une entreprise c’est un achat dans un commerce ou il faut en créé ? 

Pour mettre en place des voiture vous pouvez me contacter pour des explications ?

**Comment by antadrias** [comment]
Si j’ai bien compris c’est un système de palette a place mais comment les place les achète ? Ou un joueur spécial ?

**Comment by Lyeed** [comment]
Salut.

J'avais fais une petite explication du système en Anglais.
Je te le reposte donc ici
````
There is no company on the map because players have to build it.
The player in charge of registering companies must have the license "coop_agri".
In order to create a company he has to press the interaction button (windows by default) while targeting the new CEO.
He will have an option in his interactions menu to create a company.
He has a specify the company type and its name.
When pressing enter a construction block will appear and players will be able to gather and put materials in it.
If you want to skip the construction part as admin you can while targeting the construction block, go to the admin app and press "construire" (build)
If you don't have access to the admin app you can register your UID and permissions here (https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Staff.hpp)
````

**Comment by antadrias** [comment]
Merci pour ta réponse.
Le joueur en charge de l'enregistrement des entreprises doit avoir la licence "coop_agri". pour qu'il est la licence il faut le faire depuis la base de donné ? ou en administrateur il est possible de lui attribué?
je te pose des question car comme je suis connecté seul sur le serveur pour les réglages je ne peu encore faire avec un autre joueur des action.

**Comment by Lyeed** [comment]
La licence "coop_agri" peut etre donnés par le grade le plus élevé de la faction blufor.
Dans le cas ou tu es seul tu peux te la donner à toi même à partir de la base de données.
Tu auras cependant besoin d'un autre joueur si tu veux tester le système.
Tu dois viser le PDG de la futur entreprise pour la créer.

**Comment by antadrias** [comment]
Bonjour c'est tout bon enfin presque je ne comprend pas car j'ai 2 bug le 1er le joueur n'est pas sauvgardé et lorsque je prend l'achat d'une maison il respown pas dedans mais devantl'église

**Comment by Lyeed** [comment]
Il n'y a pas de respawn. Quand le joueur se reconnecte il est censé revenir là ou il était. Dans le cas où il meurt il reviendra à l'hopital.
Le joueur n'est pas sauvegardé, cest à dire ? Tu testes bien la mission au travers d'un processus arma3server et non en lancant la mission en client/server à partir de l'onglet multijoueur ?

**Comment by antadrias** [comment]
Il est placer sur un serveur OVH avec le arma3server64

**Comment by antadrias** [comment]
Je peu vous fournir en priver le TS du serveur ?

**Comment by Lyeed** [comment]
Je ne fais pas d'assistance de ce type sinon j'y passerais la journée.

Aucun soucis n'a été remonté concernant la sauvegarde du personnage.
Vérifie que tu n'ais pas d'erreurs client/server/extdb

**Comment by antadrias** [comment]
Vous savez ou son les log des 2 cotés car j'ai mis pas mal d'argent en investissement sur le serveur (1000euro) mais je suis bloquer juste sur le sauv profils ...

**Comment by antadrias** [comment]
je n'est pas mis extLOG ? il faut le mettre en @extLOG

**Comment by antadrias** [comment]
en gros je me connect je fait un achat je me deplace et je me deconnect correctement du serveur puis quand je me connect je reviens a l'initial argent position inv

**Comment by Lyeed** [comment]
Cela vient surement du fait que tu as loupé des étapes dans le setup du serveur.
Relis bien le README avec les informations sur la configuration à faire.

**Comment by antadrias** [comment]
J'ai tout vérifier .. rien du tout

**Comment by antadrias** [comment]
C’est bon réparé juste pour une information les joueur lorsqu’ils arrive sur le serveur il ont un grade civil de 0 il peuve quand même avoir accès au magasin ? Ou justement c’est fait exprès car un ami le plus au grade de la police ne peu pas je pense qu’il faut que je le up civil aussi ? 

Si c’est ça tu sauterai quelle fichier pour mettre de base en civil 1 ?

**Comment by antadrias** [comment]
Quand il son nouveau

**Comment by antadrias** [comment]
pour donné la licence rebelle c'est qu'elle grade ?
