### ISSUE TITLE
Dis-moi comment changer les taxes?

### ISSUE THREAD

**Issue by GelvineShore** [Lyeed/Framework_Tanoa_Life#58]
Salut
Dis-moi comment changer les taxes? À partir de la tablette "gov", les changements ne se produisent pas.

Pour vérifier la tablette de modification et appliquer [] call AlysiaServer_fnc_taxes_save; Dans la base de données, rien n'a changé.

**Comment by Lyeed** [comment]
Si modifier les taxes à partir de la tablette ne fonctionne pas tu peux modifier les valeurs directement dans la base de données. Il faudra soit redemarrer le serveur soit faire sa pendant que le serveur est éteint.

Concernant l'application taxes de la tablette, il me faudra plus d'information tel qu'un log pour avoir plus d'informations sur le problème.
