### ISSUE TITLE
Dlc obligatoire

### ISSUE THREAD

**Issue by antadrias** [Lyeed/Framework_Tanoa_Life#59]
Salut les dlc obligatoires sont lesquels car je ne trouve pas pour avoir des armes ?

Est pour la licence rebelle ça fonctionne comment ?

**Comment by Lyeed** [comment]
Il n'y a pas de DLC obligatoire il me semble depuis que Bohemia à rendu public les assets de Tanoa.

En ce qui concerne les rebelles il y a un grade civil à avoir pour pouvoir accéder à du matos au camp rebel

**Comment by antadrias** [comment]
Pour avoir le grade rebelle il faut impérativement passe par le SQL ou ont peu depuis le jeux

**Comment by antadrias** [comment]
je suis entrain de regarde sur un bug que j'ai c'est lorsque une personne veut ranger son véhicule il me dit qu'il faut attendre le reboot du serveur. le serveur ne reboot pas tout seul du coup j'ai mis un programme qui reboot tout le 4h mais pareil ont vois se message de temp en temp

**Comment by Lyeed** [comment]
Tu peux le faire à partir de l'application Admin de la tablette.

En ce qui concerne le véhicule qui ne peut pas être rangé c'est car tu as mal configuré la sauvegarde du serveur. En plus de modifier l'heure dans la config il faut que le serveur s'arrête et se redémarre apres l'heure de reboot.

**Comment by antadrias** [comment]
pour la sauvegarde du serveur c'est qu'elle config ?

**Comment by Lyeed** [comment]
Dans le README tu as tous les liens des configs importantes

**Comment by Lyeed** [comment]
La question initiale étant répondue, je clos le ticket.

**Comment by antadrias** [comment]
dernier question pour le menu admin je n'est rien pour le grade pour rebelle ?
