### ISSUE TITLE
spawn

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#6]
Bonsoir dans la db lorsqu'on veux mettre une autre faction il nous dise lorsque l'on se connecte vous n'avez pas le droit de changer de faction c pour comprendre? comment faire pour etre pompier ou policier?
Et dernière question le fichier pour déplacer la banque fédéral y en a t'il un? et comment le faire si il en existe un?
Et comment changer de vue a la troisième personne on est en seconde personne?
Mais en tous les car la mission est top fluide.Cordialement

**Comment by boubablackmamba** [comment]
Je te remercie de tes réponses rapide .
Et concernant changer la vue a la troisième personne.
Cordialement.

**Comment by Lyeed** [comment]
La vue à la troisième personne est géré par le fichier de profile du serveur.
Le seul cas qui est géré par le framework est quand il y a un tir à coté de toi, tu es bloqué à la première personne pour une minute.

**Comment by Lyeed** [comment]
Les questions initiales étant répondues, je ferme le ticket
