### ISSUE TITLE
Rebel

### ISSUE THREAD

**Issue by antadrias** [Lyeed/Framework_Tanoa_Life#61]
Bonjour je ne trouve pas les shop rebell ? ou il se situe ?

**Comment by antadrias** [comment]
BLACKMARKETS ?

**Comment by antadrias** [comment]
C’est surtout que je n’arrive pas as comprendre la condition sur les rebelle j’ai vue la condition dans les configurations staff mais ... je trouve pas, entreprise visé une personne et touche Windows en étant chef de la gendarmerie mais pour rebelle je voix pas j’ai testé un peu tout je trouve pas.

**Comment by Lyeed** [comment]
Bonjour,

GitHub n'est pas un chat instantanée pour support d'installation.
Essaye de comprendre par toi même avant de venir ici pour tes questions, ton nombres de questions et l'espacement entre ces dernières prouvent que tu ne cherches pas pour toi même.

Je clos le ticket et j'attend à avoir une question ou un problème concrêt la prochaine fois
