### ISSUE TITLE
Spawn Menu

### ISSUE THREAD

**Issue by antadrias** [Lyeed/Framework_Tanoa_Life#62]
Bonjour,

J'ai remarquer dans les fichiers qu'il y as un système de sélection lorsque ont se connect sur le serveur Pour choisir des emplacement.

Il y as des manipulation à faire pour l'active ? Ou un fichier de configuration ?

**Comment by Lyeed** [comment]
Bonjour,

Le joueur reviendra toujours à la position ou il a déconnecter.
Dans le cas où le joueur meurt il reviendra automatiquement à l'hopital.
Il n'y a pas de système d'apparition usuelle.
