### ISSUE TITLE
Vérification des logs

### ISSUE THREAD

**Issue by Oxxmo** [Lyeed/Framework_Tanoa_Life#64]
Bonjour Lyeed,
J'ai pas mal cherché mais je trouve pas la manière d'avoir des logs complets de chaques actions des joueurs sur le serveur. Ce système n'est pas en place sur le FW ?
Cordialement.

**Comment by Lyeed** [comment]
Bonjour,

Chaque action faites dans le jeu ? Tu ne trouveras aucun système qui te permet de logger autant d'informations. De plus tu aurais surement des problèmes de performance.

Le framework utilise Extlog pour logger et stocker au format texte des actions essentielles pour la modération telles que : 
- qui à tuer qui
- des informations financières au sujet du blanchiment d'argent 
- et j'en passe...

**Comment by Oxxmo** [comment]
Oui j'ai sûrement abusé dans ma recherche d'informations mdr. Je parlais des logs comme le blanchiment etc.
Donc du coup normal que je n'ai rien si Extlog n'est pas installé

**Comment by Oxxmo** [comment]
Et les fichiers extLOG (tbb, tbbmaloc etc) doivent être copié dans le @extDB3 on est d'accord?

**Comment by Oxxmo** [comment]
Oui j'ai sûrement abusé dans ma recherche d'informations mdr. Je parlais des logs comme le blanchiment etc.
Donc du coup normal que je n'ai rien si Extlog n'est pas installé

**Comment by Lyeed** [comment]
https://bitbucket.org/torndeco/extdb3/wiki/Installation
