### ISSUE TITLE
Comment mettre l'accréditation rebelle ?

### ISSUE THREAD

**Issue by Mzaaa** [Lyeed/Framework_Tanoa_Life#66]
Bonjour, je voudrais savoir ou est l'accréditation rebelle dans le menu admin, car j'ai que quelques options

**Comment by Lyeed** [comment]
Bonjour,

As tu pensé à t'ajouter à la macro situé à la première ligne du fichier de config admin ?

**Comment by Mzaaa** [comment]
Oui

**Comment by Mzaaa** [comment]
https://imgur.com/TirAQq5
https://imgur.com/ARQyLUa

**Comment by Lyeed** [comment]
Voici la condition pour ajouter la premiere accréditation
`((side (call compile (lbData[9000,lbCurSel 9000]))) isEqualTo civilian) && (((call compile (lbData[9000,lbCurSel 9000])) getVariable ['rank', 0]) != 1)`
Cela correspond à ce que je joueur que tu ais sélectionné dans menu soit de la faction civil et qu'il ne soit pas rank 1 (puisque l'accréditation correspond au rank 1)

**Comment by Mzaaa** [comment]
Ok, mais ou est le menu du coup ?

**Comment by Lyeed** [comment]
Dans le menu de ton premier screen.
J'avais effectivement oublié mais tu dois préciser des UID pour les permissions concernant les accréditations. Cela se défini à la classe accred_reb_remove.
Si tu souhaites avoir que tous les membres du staff puisse effectuer les actions des accréditations tu peux mettre `allow[]=ADMIN_AND_MODO;`

```			
                        class accred_reb_remove
			{
				name="Supprimer accréditation rebelle";
				statement="[(call compile (lbData[9000,lbCurSel 9000])), 0, player] remoteExecCall ['AlysiaServer_fnc_whitelistRebels', 2];";
				condition="((side (call compile (lbData[9000,lbCurSel 9000]))) isEqualTo civilian) && (((call compile (lbData[9000,lbCurSel 9000])) getVariable ['rank', 0]) > 0)";
				allow[]={"XXXXXXXXXXXXXXXXXX"}; <------ ICI
			};
			class accred_reb_first: accred_reb_remove
			{
				name="Accréditation rebelle 1";
				statement="[(call compile (lbData[9000,lbCurSel 9000])), 1, player] remoteExecCall ['AlysiaServer_fnc_whitelistRebels', 2];";
				condition="((side (call compile (lbData[9000,lbCurSel 9000]))) isEqualTo civilian) && (((call compile (lbData[9000,lbCurSel 9000])) getVariable ['rank', 0]) != 1)";
			};
			class accred_reb_second: accred_reb_remove
			{
				name="Accréditation rebelle 2";
				statement="[(call compile (lbData[9000,lbCurSel 9000])), 2, player] remoteExecCall ['AlysiaServer_fnc_whitelistRebels', 2];";
				condition="((side (call compile (lbData[9000,lbCurSel 9000]))) isEqualTo civilian) && (((call compile (lbData[9000,lbCurSel 9000])) getVariable ['rank', 0]) != 2)";
			};

**Comment by Mzaaa** [comment]
Merci beaucoup tu gères

**Comment by Lyeed** [comment]
Je clos l'issue.
