### ISSUE TITLE
Side

### ISSUE THREAD

**Issue by HKaoTic** [Lyeed/Framework_Tanoa_Life#68]
Bonjour, j'aimerai mettre un véhicule dans plusieurs SIDE mais j'ai essayé d'en mettre plusieurs et lorsque je veux l'acheter il marque "unknownside"
Que faut-il que je marque dans le config_vehicules ?

**Comment by Lyeed** [comment]
Tu peux retrouver la config des véhicules [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Vehicles.hpp).

Il y a un commentaire une explication concernant les sides
