### ISSUE TITLE
Base de donnée EXDB3

### ISSUE THREAD

**Issue by Quentin2002** [Lyeed/Framework_Tanoa_Life#70]
Bonjour, j'ai chercher un peu partout maiss la euh je voit pas comment fi sa

voici l'erreur

`18:37:42 "extDB3: Version: 1.028"
18:37:42 "extDB3: Error Failed to Connect to Database: [0,""Database Config Error""]`

**Comment by Lyeed** [comment]
Bonjour,

L'erreur provient du fait que tu as rentré un ou plusieurs informations incorrectes dans ta config de extdb
