### ISSUE TITLE
Je n'arrive pas a installer le serveur 

### ISSUE THREAD

**Issue by OnHeyMis** [Lyeed/Framework_Tanoa_Life#71]
Bonjour, je n'arrive pas a installer le serveur sur un serveur nitrado. Il me le met en création en me disant que il manque une signature d'un mod tu pourrai m'expliquer comment on installe le serveur.

Merci l'ami

**Comment by Lyeed** [comment]
Bonjour,

Il y a suffisamment d'information dans le README pour pouvoir installer le serveur, cela prend en compte cependant que tu sais comment installer et setup un serveur arma.
Si tu ne sais pas tu peux trouver des tutoriels, le framework n'a rien de compliqué, une mission, un addon server, une base de donnée et un pack de mods.

Concernant ton erreur de signature, je te conseil de resigner tous les mods avec ta propre signature et d'ainsi vérifier que toutes les signatures se créent bien. Si ce n'est pas le cas, repack le ou les addons en question.

**Comment by OnHeyMis** [comment]
merci mais il faut un serveur avec une base altislife ou vanilla

**Comment by Lyeed** [comment]
Je ne connais pas les présets de Nitrado mais les deux doivent pouvoir être utilisés
