### ISSUE TITLE
CfgMarker.meal_hospitals problem

### ISSUE THREAD

**Issue by MCPE933** [Lyeed/Framework_Tanoa_Life#72]
CfgMarker.meal_hospitals problem when I run server

**Comment by MCPE933** [comment]
please help me!!!!

**Comment by Lyeed** [comment]
Hi !

The server and the clients need the packmod to be activated

**Comment by MCPE933** [comment]
What's packmod??

**Comment by MCPE933** [comment]
I'm use original file on github

**Comment by Lyeed** [comment]
Maybe you forgot to read the README ?

**Comment by MCPE933** [comment]
Thank you,very much
