### ISSUE TITLE
reaparition au soins intensif

### ISSUE THREAD

**Issue by mecta02** [Lyeed/Framework_Tanoa_Life#74]
Bonjour quand je me deco et que je me reco je suis en soin intensif a chaque fois la seul piste que jessaye de comprendre est cette partie dans les log 

2019/07/28, 20:21:49 Failed attempt to execute serverCommand '#unlock' by server.
2019/07/28, 20:21:49 " :: [RCON:ALL-KICK] Loop end ::"
2019/07/28, 20:24:47 Server: Object 0:0 not found (message Type_180)
2019/07/28, 20:24:47 Server: Object 0:0 not found (message Type_180)
2019/07/28, 20:24:47 Server: Object 0:0 not found (message Type_180)
2019/07/28, 20:24:50 a3\characters_f\heads\glasses\g_shades_black.p3d: No geometry and no visual shape
2019/07/28, 20:24:50 Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
2019/07/28, 20:24:50   Error position: <addEventHandler [_x, format ['call cba_x>
2019/07/28, 20:24:50   Error Foreign error: Unknown enum value: "FiredBis"
2019/07/28, 20:24:50 File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents], line 1945
2019/07/28, 20:24:50 Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
2019/07/28, 20:24:50   Error position: <addEventHandler [_x, format ['call cba_x>
2019/07/28, 20:24:50   Error Foreign error: Unknown enum value: "InitPost"
2019/07/28, 20:24:50 File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents], line 1945
2019/07/28, 20:24:53 Ragdoll - loading of ragdoll source "Soldier" started.
2019/07/28, 20:24:53 Ragdoll - loading of ragdoll source "Soldier" finished successfully.
2019/07/28, 20:26:12 Client: Remote object 4:0 not found
2019/07/28, 20:26:12 "default/BIS_fnc_log: HandleDisconnect : CIV_1"
2019/07/28, 20:26:17 Warning: Cleanup player - person 4:8 not found
2019/07/28, 20:26:19 Warning: Cleanup player - person 4:8 not found

**Comment by Lyeed** [comment]
Bonjour,

Il s'agit d'une erreur CBA, essaye de le mettre à jour
