### ISSUE TITLE
Chemain d' accès

### ISSUE THREAD

**Issue by Jonastex** [Lyeed/Framework_Tanoa_Life#75]
Bonjour

J' ai un problème avec le fichier le fichier mod j' ai modifié le @Alysia mais les chemin d' accès ne fonctionne plus. Donc où est l' endroit pour modifié les raccourcis de chemin d' accès ?

J' ai aussi le même problème avec la mission j' ai changé le .tanoa en .kelleysIsland donc le même problème arrive.

Merci de ton aide :)

**Comment by Lyeed** [comment]
Bonjour,

Quels chemin d'accès ? @ALYSIA est juste un nom de conteneur de mods et n'a aucun impact sur son contenu. Si  tu le renommes n'oublies juste pas de modifier dans ton launcher arma et côté serveur

**Comment by Jonastex** [comment]
Salut, Oui mais pour ce qui est du mp mission j' ai changé le .tanoa pour changé de map et quand je lance mon serveur il y a plein d' erreur.

**Comment by Lyeed** [comment]
Il y a des erreurs car il y a d'autres elements à changer pour basculer une mission Arma 3 d'une carte à une autre.
Lis et comprends les erreurs, corrige les et avec persévérance tu réussiras à changer la carte.

**Comment by Jonastex** [comment]
dac merci ;)
