### ISSUE TITLE
Comment ajouter un bouton dans le menu staff ?

### ISSUE THREAD

**Issue by Quentin2002** [Lyeed/Framework_Tanoa_Life#76]
Bonsoir,

J'aimerai ajouter un bouton dans le menu staff comment faire ?

Cordialement

**Comment by Lyeed** [comment]
Bonjour,

Pour ajouter
- un bouton d'action il faut ajouter une classe dans `commands >> buttons`
- une action lié au personnage sélectionné dans la liste il faut ajouter une classe dans `commands >> target`

[Fichier](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Staff.hpp)

**Comment by Quentin2002** [comment]
ok merci
