### ISSUE TITLE
Question et probléme

### ISSUE THREAD

**Issue by Quentin2002** [Lyeed/Framework_Tanoa_Life#77]
Bonsoir,

Je viens pour plusieur choses,

D'abord les probléme,

Les atm quand on fait windows ne fonctionne pas (on est sur malden)

Ensuite que on a un sac de 100 de place ou 50 de place on reste a 24 de place 

Et la question, comment faire un certificat medical ?

Cordialement

**Comment by Lyeed** [comment]
Bonjour,

Concernant les distributeurs, ils doivent être définis [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_ATM.hpp)
Pour ce qui est des places de ton inventaires, le calcul se fait [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Inits/fn_init_loops.sqf) et se base sur la capacité du sac porté
Pour finir, le certificat médical est distribué par les membres de la faction GUER et ayant un grade adéquat.

**Comment by Quentin2002** [comment]
Ok merci mais les ATM charge pas dans ma Base de donnée, la table "lands_atm" est vide

**Comment by Lyeed** [comment]
La sauvegarde est supposée se faire quelques minutes avant l'arret automatique du serveur.
Les heures de redémarrage doivent être indiqué dans la [config du server](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Server/configs/Config_Server.hpp)
