### ISSUE TITLE
task force 

### ISSUE THREAD

**Issue by boubablackmamba** [Lyeed/Framework_Tanoa_Life#8]
problème avec tous les joueur qui se fond expulsé au bout de 45 second et task leur dit vous n'etes pas connecter au task force
cordialement

**Comment by Lyeed** [comment]
Lis le readme sur la configuration du serveur tfr

**Comment by boubablackmamba** [comment]
Je l'ai fais et suivis a la lettre moi en tant que admin pas de souci mais pour les joueur simple il on a un message qui leur dit au bout de 20 sec dans 45 sec vous serez ejecter car task ne les reconnais pas et je me suis mis en civil sans etre inscris dans le fichier staff je me fais ejecter pareil

**Comment by boubablackmamba** [comment]
J'ai remarquer que lorsqu'on es dans le staff c bon hors du staff ejecter

**Comment by Lyeed** [comment]
Lis vraiment le readme mon dieu

**Comment by Lyeed** [comment]
La réponse tant dans le readme le clos le ticket.

Indice : configuration du nom de ton serveur taskforceradio

**Comment by boubablackmamba** [comment]
Bonsoir je précise que ca va faire 100 fois que je suis le read me 
- Line 88 : Remplace YOUR TEAMSPEAK NAME by your Teamspeak's name
    
	**Exemple :**
	``
		waitUntil {(["Lyeed Tanoa Life Teamspeak", (call TFAR_fnc_getTeamSpeakServerName)] call BIS_fnc_inString)};
	``
	- Line 93 : Your channel name. Default : TaskForceRadio

et le task force switch niquel mais au bout d'une min le serveur met erreur et dit vous n'etes pas connecter sur le teamspeak du serveur. Par contre si je me met en admin nickel pas de problème

Cordialement


diag_log "<INIT> Validation de présence sur le Teamspeak ...";
		("initLayer" call BIS_fnc_rscLayer) cutText ["Validation de présence sur le Teamspeak", "BLACK FADED", 999999, true];
		waitUntil {(["Aventura", (call TFAR_fnc_getTeamSpeakServerName)] call BIS_fnc_inString)};
		diag_log "<INIT> Présence validé";

		diag_log "<INIT> En attente de validation de votre présence dans le channel TaskForceRadio...";
		("initLayer" call BIS_fnc_rscLayer) cutText ["En attente de validation de votre présence dans le channel TaskForceRadio", "BLACK FADED", 999999, true];
		waitUntil {((call TFAR_fnc_getTeamSpeakChannelName) isEqualTo "TaskForceRadio")};
		diag_log "<INIT> Présence dans le channel TaskForceRadio validé";


Et j'ai même renomer pour voir mon serveur ts en TaskForceRadio
