### ISSUE TITLE
Éjection task force

### ISSUE THREAD

**Issue by Jonastex** [Lyeed/Framework_Tanoa_Life#81]
Bonjour.

J' ai configuré task force tout est fonctionnel (switch dans le channel). J' ais fais ce que le read me demande mais quand je me connecte au serveur après 20 second il y a un message m' indiquant que je ne suis pas connecté au teamspeak. Puis ensuite après 45 seconde échec de mission (éjecté sur serveur) raison  Teamspeak. Je ne suis pas le premier a avoir cet erreur mais aucune solution n' a été donné. 

Cordialement.

**Comment by Lyeed** [comment]
Bonsoir,

Le script qui te kick se trouve dans [init_loops](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Inits/fn_init_loops.sqf).

Si cela arrive c'est que tu ne remplis pas les conditions.
En suivant le README tu as été amené a remplir une condition qui devait ressembler à
`if (!(["YOUR TEAMSPEAK NAME", call TFAR_fnc_getTeamSpeakServerName] call BIS_fnc_inString)) then`
Le nom que tu as du mettre ne doit pas correspondre

**Comment by Jonastex** [comment]
![teamspeak](https://user-images.githubusercontent.com/30275981/64193338-db2df700-ce7c-11e9-9806-f2fe429e4400.png)

Bonsoir

Voici mon init _loops sur les lignes 152 et 178 on été modifié comme est indiqué sur le README

Cordialement

**Comment by Lyeed** [comment]
C’est taskforce qui te retourne le nom actuel du teamspeak. Le framework fait simplement un inString dessus. Si ça te kick c’est que la condition n’est pas valide.

**Comment by Jonastex** [comment]
![task](https://user-images.githubusercontent.com/30275981/64195313-732ddf80-ce81-11e9-8109-e18cdb70c446.png)
Pour installé task force j' ai modifié ce init.sqf ainsi que le clientinit dans le pbo task force. Puis j' ai mit un module sur la mission. De ce coté rien. Es ce que j' ai oublié quelque chose ?

**Comment by Lyeed** [comment]
Je ne pense pas que tu ais lu correctement le readme pour setup et configurer le framework.

**Comment by Jonastex** [comment]
Bonsoir

Je vous ais envoyé des photos, et je ne vois pas d' où viens le problème. Pouvez vous me dire d' où cela vient svp ?

**Comment by Lyeed** [comment]
Le screen que tu as envoyé n'a aucun sens. Tu dois indiquer dans la config côté serveur tes informations taskforceradio ainsi que modifier les lignes indiquées dans le readme concernant le fichier fn_init_loops.sqf

**Comment by Jonastex** [comment]
problème résolu sa venais d' un membre d' infistar qui avait installé task force, il avais endommagé la mission.

Merci tu peux fermé le ticket ;)

**Comment by Lyeed** [comment]
Parfait 👍
