### ISSUE TITLE
Petit soucis avec la création des entreprises

### ISSUE THREAD

**Issue by Owned3D** [Lyeed/Framework_Tanoa_Life#82]
Bonjour, j'explique mon soucis : 

Tout marche nickel, sauf a la création d'une entreprise. Le lancement de la création de l'entreprise ce fait parfaitement, on n'ajoute les compos nécessaire a la création de l'entreprise, mais voilà une fois les compos mis, il y as pas le bouton "construire" du coup j'ai essayer de lancer la création via la base de donnée en changent la valeur de "Build" en la passant à 1. Au reboot du serveur le bâtiment ce crée, mais le PDG n'obtient pas la licence approprié et le nombre de membre dans l'entreprise reste à 0. J'ai même essayé d'ajouter la licence via la base de donnée mais celle ci s'enlève a la connection du personnage.

**Comment by Lyeed** [comment]
Bonjour,

Une fois les matériaux déposés dans l'entreprise en construction, le joueur est supposé faire appel à une entreprise de BTP pour finaliser la phase de construction.
Si il n'y a pas encore d'entreprise de BTP de disponible, un admin peut viser le tas de brique et effectuer l'action 'construire' à partir de son application admin sur la tablette.
En suivant l'un de ces deux méthodes l'entreprise sera construite de la bonne manière et il ne devrait pas y avoir d'erreur sur le PDG.

**Comment by Owned3D** [comment]
Quand tu dit "Si il n'y a pas encore d'entreprise de BTP de disponible, un admin peut viser le tas de brique et effectuer l'action 'construire' à partir de son application admin sur la tablette." c'est avec la touche windows ? sinon je n'ai pas vu l’application en question

**Comment by Lyeed** [comment]
Si tu es admin du serveur et que tu as configuré tes permissions dans le fichier de configuration du staff tu es supposé avoir une application admin sur ta tablette

**Comment by Owned3D** [comment]
Oui je l'ai mais je ne vois pas ou est le bouton pour construire xD

**Comment by Owned3D** [comment]
C'est bon :)
