### ISSUE TITLE
Quels sont les fichiers exacts à modifier pour un changement de map ?

### ISSUE THREAD

**Issue by NEYPHIS** [Lyeed/Framework_Tanoa_Life#83]
Bonjour,

Je souhaiterais changer la map de la framework vers la la map kelley's island, et j'aurais voulu savoir quels sont les fichiers exacts a modifier pour cela ?

Cordialement,
NEYPHIS

**Comment by NEYPHIS** [comment]
Bonjour, j'ai aussi un soucis avec les sac a dos TFR RADIO lorsque je n'ai n'y téléphone et ni sac a dos quand je déco reco je spawn avec un sac a dos TFR RADIO. Que faire pour y remédier ?

Cdt,

**Comment by Lyeed** [comment]
Lire #84 pour la radio
