### ISSUE TITLE
Création d'entreprise

### ISSUE THREAD

**Issue by SAYREXx** [Lyeed/Framework_Tanoa_Life#85]
Bonjour!
Après avoir créé une entreprise via le panneau d'administration, celle-ci n'est pas enregistrée dans la base de données et, après le redémarrage du serveur, il doit être créée à nouveau.
De plus, les ressources de la colonne CONSTRUCTION_require ne sont pas mises à jour dans la base de données après les avoir placées dans le bloc de construction. Quel pourrait être le problème? S'il vous plaît aider!

**Comment by Lyeed** [comment]
Bonjour,

Si les resources ne sont pas mis à jour c'est que ton serveur ne doit pas s'arrêter correctement. Il y a une phase de 1-2 minutes avant que le serveur ne s'éteigne où il sauvegarde ses données dans sa base. Il se peut cela ne se fait pas correctement, il faut laisser le serveur s'autogérer (sauvegarder, s'éteindre, se rallumer).

**Comment by SAYREXx** [comment]
Le serveur ne s'est pas arrêté automatiquement. Il y a un coup de pied du serveur et lock 
19:56:03 Successfull attempt to execute serverCommand '#lock' by server.

**Comment by Lyeed** [comment]
Le processus du serveur ne pourra pas s'arrêter à partir d'arma, tu vas devoir utiliser un script pour le faire.
Voici comment doit se dérouler un redemarrage pour que les données soient sauvegardés correctement :
4 min avant reboot : se serveur se lock et commence à expulser les joueurs restants
3-2 min avant reboot : il démarre la sauvegarde
1 minute avant reboot : la save est normalement terminée et le serveur attend de s'éteindre. C'est la qu'un acteur externe doit intervenir et couper le serveur pour le redemarrer apres l'heure de reboot.

**Comment by SAYREXx** [comment]
Bien! Et qui fait la construction finale? Est-ce que cela nécessite une sorte de licence?

**Comment by Lyeed** [comment]
La construction se termine avec l'interaction d'un membre d'un entreprise de BTP. Si aucune entreprise n'est présente tu peux utiliser le panel d'administration en jeu en visant l'entreprise sous forme de brique

**Comment by SAYREXx** [comment]
> La construction se termine avec l'interaction d'un membre d'un entreprise de BTP. Si aucune entreprise n'est présente tu peux utiliser le panel d'administration en jeu en visant l'entreprise sous forme de brique

Merci beaucoup, Lyeed! Tout fonctionne!

**Comment by Lyeed** [comment]
Formidable. Je clos le ticket :+1:
