### ISSUE TITLE
Problème du CBA

### ISSUE THREAD

**Issue by Oxxmo** [Lyeed/Framework_Tanoa_Life#86]
Bonjour Lyeed,

Après avoir essayé de mettre à jour le CBA je me confronte à plusieurs soucis : 
- Lorsque je mets à jour le CBA à jour, certaines animations comme "Mettre les mains sur la tête" n'affiche plus le raccourci. 
- Lorsque je fais quand même l'action elle se réalise, mais lorsque je veux les enlever, il me dit "Une action est déjà en cours".

De plus, lorsque l'on ajoute des mod "récent" cette erreur apparaît continuellement dans les logs :

 `Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
  Error position: <addEventHandler [_x, format ['call cba_x>
  Error Foreign error: Unknown enum value: "FiredBis"
File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents]..., line 1945`

ou alors 
`Error in expression <f (!isClass _eventClass) then {
{
_unit addEventHandler [_x, format ['call cba_x>
  Error position: <addEventHandler [_x, format ['call cba_x>
  Error Foreign error: Unknown enum value: "InitPost"
File \x\cba\addons\xeh\fnc_initEvents.sqf [CBA_fnc_initEvents]..., line 1945`

Merci pour ta réponse.

Cordialement.

**Comment by Lyeed** [comment]
Il va falloir plus d'informations, mais premièrement peux-tu essayer de vider ton cache de keybind CBA ?
`profileNamespace setVariable ["cba_keybinding_registrynew", nil]; saveProfileNamespace;`

Pour ce qui est des messages d'erreurs CBA es-tu sur qu'ils s'affichent lors de l'action et non lors du démarrage du jeu ?

Quelle action te retournent `Une action est déjà en cours` ? Car il ne me semble pas que `mettre les mains sur la tête` puisse t'afficher ce message

**Comment by Oxxmo** [comment]
Je vais vider le cache dans la soirée. 
On est daccord je l'exécute depuis la commande de debug directement sur le serveur ?
Non les messages s'affichent continuellement sans faire une action. C'est régulier et non lié à une action en particulier.

**Comment by Lyeed** [comment]
> On est daccord je l'exécute depuis la commande de debug directement sur le serveur ?

Oui en local à partir de la debug console


> Non les messages s'affichent continuellement sans faire une action. C'est régulier et non lié à une action en particulier.

Il se peut également que cela provienne de taskforceradio qui ne doit pas suivre les mises à jour CBA


> L'action qui me retourne le message d'erreur c'est lorsque je souhaite enlever les mains que j'ai en l'air.

Es-tu sur que l'on parle de l'action surrender ? Car comme tu peux le voir il n'y a pas ce message dans [la fonction](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Game/Actions/fn_surrender.sqf).

**Comment by Oxxmo** [comment]
Je te ferais une vidéo ou quelque chose de plus explicite ça sera plus simple.

**Comment by Oxxmo** [comment]
Alors, voici des nouvelles : 

- J'ai maj le CBA avec la dernière version. Plus d'erreur de script comme dit plus haut

**Comment by Lyeed** [comment]
Tu essayes de lancer une animation non ? Car le message `Vous ne pouvez pas effectuer une animation alors que vous avez les mains sur la tête.` doit provenir de la fonction [anim_play](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/core/Game/Actions/fn_animPlay.sqf). Il est normal de pas pouvoir jouer une animation alors que tu es en mode "surrender".

Concernent les erreurs lors du menu il s'agit de `cba_keybinding_dikdectostringtable` qui n'est pas défini. Cela concerne plus CBA que mon framework, je te redirige donc vers eux pour essayer de savoir pourquoi la variable n'est pas déifinie. Cela peut être du aux mises à jours qui peuvent comporter des breaking changes.

**Comment by Lyeed** [comment]
Je clos, si un problème persiste merci de refaire une issue en reprécisant votre soucis.
