### ISSUE TITLE
Re:Sac radio longue porté

### ISSUE THREAD

**Issue by Jonastex** [Lyeed/Framework_Tanoa_Life#87]
https://github.com/Lyeed/Framework_Tanoa_Life/issues/84

Bonjour

Excusez mon retard. J' ai exploré les solutions que vous m' avez donné il n' y a rien dans l init de la mission qui définie qu' il y a un give de radio au spawn d' un civil. De plus dans l' éditeur j' ai le même problème donc je pense que cela vient des mods. Mais que je ne sais pas lequel pose problème.

**Comment by Lyeed** [comment]
Bonjour,

Tu peux retrouver ici les définitions qui font que le joueur ne reçoit pas de radio lors de sa connexion
https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/init.sqf

**Comment by Jonastex** [comment]
Problème réglé le bug venais des mes modification.

Merci
