### ISSUE TITLE
Question Admin Menu

### ISSUE THREAD

**Issue by xtr3m598** [Lyeed/Framework_Tanoa_Life#88]
Bonjour , 
Je pense avoir un problème au niveau du menu admin car il ne m'affiche pas toute les interaction que je devrait avoir malgré que j'ai mis mon uid dans le define et d'avoir crée une class admin  
certaine sont sous condition mais par exemple je ne peux pas construire d'entreprise avec le menu admin alors que pourtant le bouton est bien présent dans le fichier config staff

Comment pourrait je faire pour solutionné le problème ?

Merci D'avance :)

**Comment by Lyeed** [comment]
Bonjour,

Si tu as bien indiqué ton UID dans la define et dans la classe, il ne devrait pas y avoir de problème.
La classe que tu as créée et qui comprend ton UID, hérite t-elle de la classe admin par défaut ?

Est-tu sur de remplir les conditions pour effectuer l'action ? Pour le cas d'une entreprise, l'action n'est proposée que lorsque tu vises un entreprise en construction (le tas de briques) par exemple.

**Comment by xtr3m598** [comment]
Bonjour ,

oui j'ai bien indiquer l'uid dans le define et j'ai crée une nouvelle classe admin comme ceci :

**Comment by xtr3m598** [comment]
Bonjour , 

Désoler pour le temps de réponse , oui j'ai bien indiqué mon uid dans le define et j'ai crée une classe admin (voir ci dessous , j'ai remplacé mon uid arma par simplement uid pour éviter des soucis en publiant cela ici)

https://pastebin.com/5DmFxhQy

Ensuite effectivement j'ai bien repris connaissance du fichier et effectivement j'avait mal regarder au niveau de la condition donc je pense que je possède bel et bien toute les fonctions du panel admin .

Cependant j'aurait besoin d'information concernant les entreprises , j'ai bien chercher dans les issue mais je trouve pas clairement les réponses à mes questions , mes questions sont les suivantes : 

- Ou et Comment peut t'on se procuré les licence entreprise ?
- Comment sont gérer les traitements des ressources pour les civils (non entrepreneur) ?

J'ai également un soucis enfin un presque soucis au lancement du serveur , pendant le démarrage arma 3 me notifie que Tanoa-Server à besoin d'extDB3 pour fonctionné hors si je fait ok le serveur se lance correctement et je n'ai aucun soucis de bdd comment pourrait-je solutionné ce presque soucis ? 

Si il faut que je crée une nouvelle issue pour mon soucis ci dessus faite le moi savoir .

Merci d'avance ;)

**Comment by Lyeed** [comment]
Bonjour,

Les licenses d'entreprises sont achetés par le PDG d'une entreprise directement à ses membres à partir du panel si mes souvenirs sont bons.

Les civils qui veulent se faire de l'argent avec des ressources d'entreprises peuvent soit postuler directement soit proposer ses services extérieurs en fournissant l'entreprise en matériaux désirés.

Extdb3 est requis pour fonctionner. Sans cela les scripts serveur ne doivent même pas s'éxécuter.
Si vous arrivez à atteindre la phase de jeu c'est que cela doit marcher.

Cordialement

**Comment by svenhp** [comment]
Salut, dis-moi comment mettre une personne en prison?

**Comment by Lyeed** [comment]
Le système de prison n'a jamais été complètement fini et n'est donc pas fonctionnel.
Tu vas devoir y apporter des modifications toi même avant de pouvoir mettre des gens en prison :)

Je clos le ticket.
