### ISSUE TITLE
Lancement du serveur ne veut pas ce lancer

### ISSUE THREAD

**Issue by KillianDubois** [Lyeed/Framework_Tanoa_Life#9]
Bonjour/Bonsoir,

Je vous contacte aujourd'hui pour vous demandez votre aide a mon problème.
Le voici:
Quand je lance mon .bat il charge tout les addon jusqu'au moment où il veut lancer la mission il me dit ceci: 
---------------------------
Arma 3
---------------------------
File , line 1: Config: End of line encountered after Tanoa-Server
---------------------------
OK   
---------------------------
Cordialement

**Comment by Lyeed** [comment]
Bonsoir,

Doublon. Merci de se référer à https://github.com/Lyeed/Framework_Tanoa_Life/issues/3
