### ISSUE TITLE
traitement des ressouces ( logo orange )

### ISSUE THREAD

**Issue by Egaria** [Lyeed/Framework_Tanoa_Life#90]
Salut Lyeed,

Je cherche encore comment mettre en place les traitements des ressources comme une personne à dit dans le ticket #27 
Car sans rien toucher à la mission je n'ai pas ces traitement de ressource ( logo orange )

bonne journée

**Comment by Lyeed** [comment]
Bonjour,

Les marqueurs sont liés à des entreprises. Une fois construite un marqueur devrait être disponible

**Comment by Egaria** [comment]
Donc on ne peut pas faire un traitement par PNJ comme il y avait avant ?

**Comment by Lyeed** [comment]
Il n'y a pas de "comme avant". La dernière version d'Alysia fonctionnait déjà de cette manière

**Comment by Egaria** [comment]
![image](https://user-images.githubusercontent.com/30078211/76851545-bb26b980-6849-11ea-8b61-728b9ea5a83f.png)

**Comment by Lyeed** [comment]
Je ne sais pas de quand date ton screen mais le framework à dû évoluer depuis.

Le menu de traitement que l'on voit sur le screen doit toujours être dans la mission, tu dois toujours pouvoir refaire ca à partir du SQM si tu appels la fonction de traitement.

**Comment by Egaria** [comment]
Ok ok je viens de trouver en reprenant le shop des medics merci ;)
Et sinon normal que le serveur ne se lock pas correctement ? Et ne kick pas les gens lors des reboots ?

**Comment by Lyeed** [comment]
> Et sinon normal que le serveur ne se lock pas correctement ? Et ne kick pas les gens lors des reboots ?

Le mot de passe rcon est indiqué dans le fichier de config serveur ?

**Comment by Egaria** [comment]
Oui j’ai laissé « ChangeMe » pour tester et dans tadst j’ai mis le même

**Comment by Lyeed** [comment]
Si le serveur essaye de kick ou de se lock et qu'il n'y arrive pas, tu devrais en retrouver des traces dans ses logs.

**Comment by Egaria** [comment]
J'ai ceci en erreur dans le RPT :

Failed attempt to execute serverCommand '#lock' by server.
Failed attempt to execute serverCommand '#unlock' by server.

**Comment by Egaria** [comment]
> Si le serveur essaye de kick ou de se lock et qu'il n'y arrive pas, tu devrais en retrouver des traces dans ses logs.

Car j'arrive à me connecter depuis un logiciel pour le RCON, mais j'ai changé le port RCON j'ai mis le '2309' ce serrait pas ça le problème ?

**Comment by Lyeed** [comment]
> Car j'arrive à me connecter depuis un logiciel pour le RCON, mais j'ai changé le port RCON j'ai mis le '2309' ce serrait pas ça le problème ?

`getText(configFile >> "Cfg_Server" >> "rcon_password") serverCommand _this;`
voici la ligne de code utilisée pour le kick/lock/unlock

Documentation : https://community.bistudio.com/wiki/serverCommand

**Comment by Lyeed** [comment]
La soucis initial étant corrigé, le clos l'issue.
