### ISSUE TITLE
Pb récupération données personnage 

### ISSUE THREAD

**Issue by heretic08000** [Lyeed/Framework_Tanoa_Life#94]
Bonjour Lyeed, je viens vers toi car j'ai un soucis avec ton framework depuis les mises a jours Bohemia
En effet, il y a 1 ans nous avons fait un serveur avec des amis en utilisant ton framework (merci du partage au passage) il fonctionnait très bien puis nous avons du le fermer, il y a 3 jours nous avons voulu le réouvrir. Les fichiers du framework et du serveur ont été mi a jour là n'est pas le probleme 

j'ai un soucis lorsque je choisis mon emplacement dans le lobby et que quelqu'un ce connecte, le switch vers le canal taskforceradio est ok mais lors du chargement se bloque a " récupération des données du personnage"

ma connection a la DB est Ok cf les lignes suivante du rpt  

CallExtension loaded: extDB3 (C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Server\@extDB3\extDB3_x64.dll) [1.0.3.2] [1.0.3.2]

"extDB3 Loaded"

le serveur quand a lui tourne très bien car la maj de la bourse, le reboot du serveur etc fonctionnent
il est bien lock et unlock pendant les inits 

je precise que j'ai essayé de remettre ton framework de base et nom celui que nous avons modifier et le résultat est le même

seulement il y a un probleme je pense avec l'execution des scripts par le client sur le serveur comme tu peut le voir a la fin du rpt lors d'une connection client

Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
Scripting function 'san_fnc_sendjipinfo' is not allowed to be remotely executed
Scripting function 'alysiaserver_fnc_query_select_...' is not allowed to be remotely executed

le 'alysiaserver_fnc_query_select_...' permettant entre autre de recupérer les infos du joueur dans la DB si son execution n'est pas autoriser par le client je pense que le soucis viens de là, j'ai désactiver battleeye coté client ainsi que serveur mais toujours le même probleme donc ce n'est pas lui qui pose probleme  

voila la partie init server du rpt :

"-------------------------------------------------------------"
"-------------------- Starting Server Init -------------------"
"-------------------------------------------------------------"
"extDB3: Version: 1.032"
"extDB3: Connected to Database"
"extDB3: Initalized SQL_CUSTOM Protocol"
"extDB3: Locked"
"[DYNAMIC MARKERS] Initializing"
"sc/BIS_fnc_log: [postInit] CBA_fnc_postInit (65.0024 ms)"
"sc/BIS_fnc_log: [postInit] KA_fnc_boltAction_postInit (0 ms)"
"sc/BIS_fnc_log: [postInit] TFAR_fnc_TaskForceArrowheadRadioInit (0 ms)"
"Creating dynamic marker cocaine_field_marker_1"
" :: [RCON:ALL-KICK] Loop begin ::"
Failed attempt to execute serverCommand '#lock' by server.
"Creating dynamic marker cannabis_field_marker_1"
"Creating dynamic marker meth_field_marker_1"
"Creating dynamic marker heroin_field_marker_1"
"Creating dynamic marker mushroom_field_marker_1"
"Creating dynamic marker launder_marker_1"
"Linked object for launder_marker_1 placed"
"Creating dynamic marker blackMarket_marker_1"
"Linked object for blackMarket_marker_1 placed"
"sc/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 2832 ms -----"
"Creating dynamic marker blackMarket_marker_2"
"Linked object for blackMarket_marker_2 placed"
"Creating dynamic marker cars_seller_marker_1"
"Linked object for cars_seller_marker_1 placed"
"Creating dynamic marker cars_seller_marker_2"
"Linked object for cars_seller_marker_2 placed"
"Creating dynamic marker drugs_seller_marker_1"
"Linked object for drugs_seller_marker_1 placed"
"Creating dynamic marker drugs_seller_marker_2"
"Linked object for drugs_seller_marker_2 placed"
"Creating dynamic marker archeologie_field_marker_1"
"Creating dynamic marker renovation_marker"
"Linked object for renovation_marker placed"
"Creating dynamic marker pillage_field_marker_1"
"Creating dynamic marker soufre_process_marker_1"
"Linked object for soufre_process_marker_1 placed"
"Creating dynamic marker rebel_marker_1"
"Linked object for rebel_marker_1 placed"
"Creating dynamic marker rebel_marker_2"
"Linked object for rebel_marker_2 placed"
"Creating dynamic marker corail_field_marker_1"
"[DYNAMIC MARKERS] Ready"
"[PHONE] Setup"
"[PHONE] Ready"
"[LABORATORIES] Setup"
"0 laboratory(s) loaded"
"[LABORATORIES] Ready"
"[VEHICLES] Loading"
"[VEHICLES] Ready"
"[BOURSE] Setup"
"[BOURSE] Ready"
"[HOUSE] Setup"
"[BOURSE] Starting market loop..."
"0 house(s) loaded succefully"
"0 house(s) failed"
"[HOUSE] Ready"
"[FACTION] Setup"
"Faction CIV | Bank=0"
"Faction EAST | Bank=0"
"Faction GUER | Bank=0"
"Faction WEST | Bank=0"
"[FACTION] Ready"
"[BUILDINGS] Init"
"[BUILDINGS] Ready"
"[COMPANIES] Setup"
"0 companie(s) loaded"
"[COMPANIES] Ready"
"[ATM] Setup"
a3\structures_f_exp\signs\companies\cornerads_01_v2_f.p3d: No geometry and no visual shape
"[ATM] Ready"
"[TAXES] Setup"
"Loading taxe [Taxe foncière] : 20%"
"Loading taxe [Taxe salariale] : 40%"
"Loading taxe [Taxe d'habitation] : 20%"
"Loading taxe [Cotisation salariale] : 20%"
"[TAXES] Ready"
"[FUEL STATIONS] Loading ..."
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Placement slopelandcontact failed on model a3\structures_f_exp\walls\net\netfence_01_m_8m_nolc_f.p3d. Missing landcontact or no points in it.
Strange convex component16 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
Strange convex component25 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
Strange convex component26 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
Strange convex component27 in a3\boat_f_gamma\boat_civil_04\boat_civil_04_f.p3d:geometryView
"[FUEL STATIONS] Fuel Stations Ready"
"[TIME] Setup"
"Date : 24 Octobre 2020"
"[TIME] Ready"
"[CLEANUP] Setup"
"[CLEANUP] Ready"
"[CLEANUP] loop cleanup vehicules & items"
"Prochain redémarrage à 20:00 (~ 284 minutes)."
"Il est 15:16"
"---------------------------------------------------------------------------------------------------------"
"Total Execution Time 32.121 seconds"
"---------------------------------------------------------------------------------------------------------"
Failed attempt to execute serverCommand '#unlock' by server.
" :: [RCON:ALL-KICK] Loop end ::"
Server: Object 0:0 not found (message Type_180)
Server: Object 0:0 not found (message Type_180)
a3\weapons_f\binocular\nvg_proxy.p3d: No geometry and no visual shape
a3\characters_f_beta\heads\glasses\g_shades_red.p3d: No geometry and no visual shape
Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
Scripting function 'san_fnc_sendjipinfo' is not allowed to be remotely executed
Scripting function 'alysiaserver_fnc_query_select_...' is not allowed to be remotely executed
Client: Remote object 4:0 not found
"sc/BIS_fnc_log: HandleDisconnect : CIV_1"
Warning: Cleanup player - person 2:785 not found
Warning: Cleanup player - person 2:785 not found

donc aurai tu une solution a me proposer car là je seche 
Merci d'avance 
Cordialement

**Comment by Lyeed** [comment]
Bonjour @heretic08000 

Tout d'abord merci pour ton issue claire et précise.

Ces erreurs doivent effectivement être l'explication du comportement que tu as décris.

```
Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
Scripting function 'san_fnc_sendjipinfo' is not allowed to be remotely executed
Scripting function 'alysiaserver_fnc_query_select_...' is not allowed to be remotely executed
```
A mon avis cela est causé par les filtres que tu peux indiquer dans la classe CfgRemoteExec.
Cf: https://community.bistudio.com/wiki/Arma_3_CfgRemoteExec

Je n'avais pas pris le temps de le faire pour la mission et elle ne devrait donc pas être présente dans la mission.

Avez-vous de votre côté inclue cette classe dans votre mission ?

**Comment by heretic08000** [comment]
Merci de ta réponse aussi rapide effectivement honte a moi j'avais complétement oublier CfgRemoteExec donc pour ceux et celles qui ont ce problème voilà le fichier description.ext  modifier (retirer le .txt et le mettre dans la partie client)

[description.ext.txt](https://github.com/Lyeed/Framework_Tanoa_Life/files/4476357/description.ext.txt)

sa remarche parfaitement merci a toi Lyeed

sujet clos pour ma part ;-)

**Comment by Lyeed** [comment]
Super, je clos.
