### ISSUE TITLE
mpmissions ; Item86 ; Skyline_Alysia

### ISSUE THREAD

**Issue by Gaetasse2013** [Lyeed/Framework_Tanoa_Life#95]
Bonjour,
Je suis nouveau dans la création de serveur et je me suis heurté à un petit problème. 
Je travail sur un serveur créé sur mon pc perso (Windows 10).
Après avoir suivi les procédures afin d'avoir le serveur en place quand je lance celui-ci la mission ne se charge pas et il apparait ceci dans les logs : 

Warning Message: mpmissions\Tanoa-Life.Tanoa\mission.sqm/Mission/Entities/Item86.type: Vehicle class Skyline_Alysia_Stand_01_F no longer exists
Warning Message: No entry 'bin\config.bin/CfgMarkers.Maels_sell'.

Y'a t-il un addon que j'aurais oublié de télécharger malgrè que j'ai suivi le tutoriel avec le @Alysia complet dans la racine.
Merci de votre aide et de votre partage.

**Comment by Lyeed** [comment]
Bonjour,

Avez-vous pensé à inclure le pack de mods aussi côté serveur ?

**Comment by Gaetasse2013** [comment]
Salut,
Je ne sais pas d'où sa venait mais avec mes collègues à force d'essayer de réinstaller le serveur depuis le début sa a marché. Et oui j'avais bien installé le pack de mods.
Désolé, je n'ai pas pu répondre avant.

**Comment by Lyeed** [comment]
Parfait. Je clos.
