### ISSUE TITLE
Nom des tenues dans l'inventaire

### ISSUE THREAD

**Issue by Gaetasse2013** [Lyeed/Framework_Tanoa_Life#98]
Bonjour,
Je cherche le fichier qui permet de changer le nom des tenues en jeu dans l'inventaire.
Celui du shop des tenues avec le name tout est bon mais lorsque je passe ma souris sur les tenues dans l'inventaire comme pour celle de la Garde de Malieu il y a toujours le GDM. Peut-on y modifier ?
De plus, pour changer "L’hôpital de Malieu" en écriture blanche qui indique l'endroit où on se situe, il s'agirait de quel fichier ?
Merci de votre aide.

**Comment by Lyeed** [comment]
Bonjour,

Pour modifier le nom d'un objet il faut passer par sa config directement dans le pack de mods et modifier l'attribut `displayName`.
Je ne saurais plus vous dire dans quel mod exactement se trouve les tenues en question.

Concernant l’hôpital de Malieu, le marqueur doit se trouver dans le fichier .sqm que vous pouvez ouvrir directement avec l'éditeur de scénarios.
Dans l'éditeur vous pourrez déplacer et changer le style des marqueurs.

**Comment by Gaetasse2013** [comment]
Pour le premier point j'ai réussi à changer. Merci beaucoup. Mais sur le deuxième point pour l'hôpital je n'ai ni trouvé de Malieu dans ma mission .sqm dans notepad++, ni trouvé dans l'éditeur que se soit par rapport au marqueur ou non ... Ce que cherche à faire est d'avoir le message "Hôpital" et non "Hôpital de Malieu" lorsque l'on spawn à cette endroit. Je me suis peut être mal exprimé précédemment.

**Comment by Lyeed** [comment]
Ah, je pense que ce que tu cherches est dans ce [fichier](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/onPlayerRespawn.sqf) - ligne 70

**Comment by Gaetasse2013** [comment]
Merci de ton aide ça a marché. Bonne soirée/journée.

**Comment by Lyeed** [comment]
Merci, également. Je clos.
