### ISSUE TITLE
Sirène (ITEM)

### ISSUE THREAD

**Issue by FRAzura** [Lyeed/Framework_Tanoa_Life#99]
Bonjour,

Sur l'aide du menu Y la touche pour activer est shift+F cependant la sirène ne se déclenche pas, savez-vous comment résoudre ce problème ?

**Comment by Lyeed** [comment]
Bonjour,

Pour activer une sirène il faut que le véhicule ait un item spécifique dans son coffre.
Ils sont listés [ici](https://github.com/Lyeed/Framework_Tanoa_Life/blob/master/Tanoa-Life.Tanoa/configs/GameConfigs/Config_Horns.hpp)

**Comment by FRAzura** [comment]
Merci, j'ai trouvé ;)

**Comment by Lyeed** [comment]
Parfait. Je clos l'issue.
